"""The heirlooms the mod offers, in the menu's order, the first by default, as their
cosmetics/heirloom/<heirloom>/heirloom.json (and painted.json) set them, with their reasons. Generated
by cosmetics/heirloom/outils/catalog_module.py: edit the JSON and run the tool, never this file.
"""

OFFERED = ('jakobs_knife', 'axe')
DEFAULT = 'jakobs_knife'
HEIRLOOMS = {'jakobs_knife': {'model': '/Game/ApexHeirloom/SM_ApexHeirloom_JakKnife.SM_ApexHeirloom_JakKnife',
                  'container': '000_ApexHeirloom_999_P',
                  'hold': {'size': 62.0, 'pitch': -44.7, 'yaw': 73.8, 'roll': -41.1, 'grip': [0.0, 0.0, 6.0]},
                  'skins': [{'name': 'own',
                             'slots': {'Base_Mat': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_01_Ruins.M_LEG_01_Ruins',
                                                    'scalars': [{'name': 'UV_Scale_Global',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.550000011920929},
                                                                {'name': 'JAK_Filigree_Tiling',
                                                                 'association': 0,
                                                                 'index': 0,
                                                                 'value': 22.0},
                                                                {'name': 'Wear',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0},
                                                                {'name': 'Rust',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0},
                                                                {'name': 'Dirt',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0},
                                                                {'name': 'SunDamage',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0}],
                                                    'vectors': [{'name': 'DL_Placement',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': [-5.0, 0.0, 0.0, 0.0]},
                                                                {'name': 'DL_Maliwan_Placement',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': [-5.0, 0.0, 0.0, 0.0]}],
                                                    'textures': [{'name': 'C1',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C1.T_JAK_GRN_C1'},
                                                                 {'name': 'C2',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C2.T_JAK_GRN_C2'},
                                                                 {'name': 'C3',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C3.T_JAK_GRN_C3'},
                                                                 {'name': 'Base_Normal',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_N.T_JAK_GRN_N'}]},
                                       'Tech_Mat': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_01_Ruins_Glass.M_LEG_01_Ruins_Glass',
                                                    'scalars': [{'name': 'Wear',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0},
                                                                {'name': 'Rust',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0},
                                                                {'name': 'Dirt',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0},
                                                                {'name': 'SunDamage',
                                                                 'association': 2,
                                                                 'index': -1,
                                                                 'value': 0.0}],
                                                    'vectors': [],
                                                    'textures': [{'name': 'C1',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C1.T_JAK_GRN_C1'},
                                                                 {'name': 'C2',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C2.T_JAK_GRN_C2'},
                                                                 {'name': 'C3',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C3.T_JAK_GRN_C3'},
                                                                 {'name': 'Base_Normal',
                                                                  'association': 2,
                                                                  'index': -1,
                                                                  'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_N.T_JAK_GRN_N'}]}},
                             'glow': None}],
                  'lists': {'default': 'apex',
                            'container': '000_HeirloomLists_999_P',
                            'folders': {'apex': 'HeirApx', 'borderlands': 'HeirBrd'}}},
 'axe': {'model': '/Game/ApexHeirloom/SM_ApexHeirloom_AxePainted.SM_ApexHeirloom_AxePainted',
         'container': '000_ApexHeirloomAxe_999_P',
         'hold': {'size': 100.0, 'pitch': -26.27, 'yaw': -0.53, 'roll': -2.55, 'grip': [-0.22, -0.184, 8.252]},
         'skins': [{'name': 'own',
                    'slots': {'Skin': {'parent': '/Game/PlayerCharacters/_Shared/Model/Materials/MI_PlayerCharacter_NonColorized.MI_PlayerCharacter_NonColorized',
                                       'textures': [{'name': 'Base Color Map',
                                                     'association': 0,
                                                     'index': 0,
                                                     'value': '/Game/ApexHeirloom/T_ApexHeirloom_AxePainted_C.T_ApexHeirloom_AxePainted_C'},
                                                    {'name': 'AORM Map',
                                                     'association': 0,
                                                     'index': 0,
                                                     'value': '/Game/ApexHeirloom/T_ApexHeirloom_AxePainted_RM.T_ApexHeirloom_AxePainted_RM'},
                                                    {'name': 'Normal Map',
                                                     'association': 0,
                                                     'index': 0,
                                                     'value': '/Game/ApexHeirloom/T_ApexHeirloom_AxePainted_N.T_ApexHeirloom_AxePainted_N'},
                                                    {'name': 'T_Emissive_Mask',
                                                     'association': 0,
                                                     'index': 1,
                                                     'value': '/Game/ApexHeirloom/T_ApexHeirloom_AxePainted_E.T_ApexHeirloom_AxePainted_E'}],
                                       'vectors': [{'name': 'Emissive Color (Red Channel)',
                                                    'association': 0,
                                                    'index': 1,
                                                    'value': [1.0, 0.0, 0.0, 1.0]},
                                                   {'name': 'Emissive Color (Green Channel)',
                                                    'association': 0,
                                                    'index': 1,
                                                    'value': [0.0, 1.0, 0.0, 1.0]},
                                                   {'name': 'Emissive Color (Blue Channel)',
                                                    'association': 0,
                                                    'index': 1,
                                                    'value': [0.0, 0.0, 1.0, 1.0]}]}},
                    'glow': {'slot': 'Skin',
                             'scalars': [{'name': 'Emissive Intensity (Red Channel)', 'association': 0, 'index': 1},
                                         {'name': 'Emissive Intensity (Green Channel)',
                                          'association': 0,
                                          'index': 1},
                                         {'name': 'Emissive Intensity (Blue Channel)',
                                          'association': 0,
                                          'index': 1}],
                             'strengths': [1.0, 1.6, 2.5, 4.0, 6.4]}},
                   {'name': 'jakobs_knife',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_01_Ruins.M_LEG_01_Ruins',
                                       'scalars': [{'name': 'UV_Scale_Global',
                                                    'association': 2,
                                                    'index': -1,
                                                    'value': 0.550000011920929},
                                                   {'name': 'JAK_Filigree_Tiling',
                                                    'association': 0,
                                                    'index': 0,
                                                    'value': 22.0},
                                                   {'name': 'Wear', 'association': 2, 'index': -1, 'value': 0.0},
                                                   {'name': 'Rust', 'association': 2, 'index': -1, 'value': 0.0},
                                                   {'name': 'Dirt', 'association': 2, 'index': -1, 'value': 0.0},
                                                   {'name': 'SunDamage',
                                                    'association': 2,
                                                    'index': -1,
                                                    'value': 0.0}],
                                       'vectors': [{'name': 'DL_Placement',
                                                    'association': 2,
                                                    'index': -1,
                                                    'value': [-5.0, 0.0, 0.0, 0.0]},
                                                   {'name': 'DL_Maliwan_Placement',
                                                    'association': 2,
                                                    'index': -1,
                                                    'value': [-5.0, 0.0, 0.0, 0.0]}],
                                       'textures': [{'name': 'C1',
                                                     'association': 2,
                                                     'index': -1,
                                                     'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C1.T_JAK_GRN_C1'},
                                                    {'name': 'C2',
                                                     'association': 2,
                                                     'index': -1,
                                                     'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C2.T_JAK_GRN_C2'},
                                                    {'name': 'C3',
                                                     'association': 2,
                                                     'index': -1,
                                                     'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_C3.T_JAK_GRN_C3'},
                                                    {'name': 'Base_Normal',
                                                     'association': 2,
                                                     'index': -1,
                                                     'value': '/Game/Gear/GrenadeGadgets/Manufacturer/JAK/Textures/T_JAK_GRN_N.T_JAK_GRN_N'}]}},
                    'glow': None},
                   {'name': 'hacker',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_03_Hacker.M_LEG_03_Hacker'}},
                    'glow': None},
                   {'name': 'storm',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_05_Storm.M_LEG_05_Storm'}},
                    'glow': None},
                   {'name': 'blood',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_16_Blood.M_LEG_16_Blood'}},
                    'glow': None},
                   {'name': 'sports',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary_Variants/M_LEG_Sports.M_LEG_Sports'}},
                    'glow': None},
                   {'name': 'moxxi',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary_Variants/M_LEG_Moxxi.M_LEG_Moxxi'}},
                    'glow': None},
                   {'name': 'legendary_04',
                    'slots': {'Skin': {'parent': '/Game/Gear/_Shared/Materials/Materials/_Global/Legendary/M_LEG_04.M_LEG_04'}},
                    'glow': None}],
         'lists': {'default': 'apex',
                   'container': '000_HeirloomListsAxe_999_P',
                   'folders': {'apex': 'AxeApex', 'borderlands': 'AxeBord'}}}}
