# Generated by sync_menu_ui; edit canonical sources.
"""Design authority for the settings window: the tokens of Kevin's approved mockup v2, in CSS pixels.

outils/export_menu_tokens.py writes the mockup's tokens.css from this file. On 2026-09-21 the values had been
copied by hand into the mod, drifted, and Kevin saw a different window in game than the one he approved.
Names follow the mockup's CSS variables: COLOR_GOLD is --color-gold.
"""

from . import menu, pack

# Colours, sRGB hex as in the mockup: black, ember red, orange and yellow from Kevin's reference image.
COLOR_WINDOW = "1e0906"
COLOR_HEADER = "2b0c07"
COLOR_SIDEBAR = "140605"
COLOR_CARD = "120504"
COLOR_HOVER = "3d1109"
COLOR_SPARK = "ff7a1a"
COLOR_GOLD = "ffd21f"
COLOR_GOLD_HI = "ffe45c"
COLOR_GOLD_SHADE = "5a3a00"
COLOR_TEXT = "f6ead6"
COLOR_TEXT_DIM = "b09274"
COLOR_TRACK = "3a120c"
COLOR_INK = "000000"
# A switched-off button's fill, and gold text laid on a card: roles of their own because the light theme needs them
# apart from the ink and the gold, beige on a black box and yellow on cream being unreadable.
COLOR_OFF = "000000"
COLOR_GOLD_TEXT = "ffd21f"
OPACITY_DISABLED = 0.35

# Type: Anton for titles (closest free font to the Borderlands logo), Barlow Condensed for the rest.
WEIGHT_REGULAR = 500
WEIGHT_MEDIUM = 600
WEIGHT_BOLD = 800
TEXT_2XS = 15
TEXT_XS = 17
TEXT_SM = 18
TEXT_MD = 20
TEXT_LG = 24
TEXT_HERO = 58
TEXT_LOGO = 64
TRACKING_SM = 0.5
TRACKING_MD = 1
TRACKING_LG = 1.5
TRACKING_XL = 3
LEADING_NONE = 1
LEADING_TIGHT = 1.05
LEADING_SNUG = 1.15
LEADING_BODY = 1.3

# Ink: the comic-book black outline and hard offset shadow.
STROKE_THIN = 2
STROKE = 3
STROKE_THICK = 4
TEXT_STROKE = 7
SHADOW_SM = 3
SHADOW_MD = 5
SHADOW_LG = 7
SHADOW_XL = 14

# Shapes, in degrees for the angles.
RADIUS_SM = 4
RADIUS_MD = 6
SLANT = -12
TILT_LOGO = -3
TILT_TITLE = -2
HAZARD_ANGLE = -45
HAZARD_STRIPE = 18
HAZARD_HEIGHT = 14
# Conflict warning, drawn in the mockup of 2026-09-22 and not in game yet: an orange square turned into a diamond
# behind a "!", on a sidebar line and on the Conflicts tab. Its shape, not only its colour, sets it apart.
TILT_WARNING = 45
WARNING_SIZE = 18

SPACE_1 = 4
SPACE_2 = 8
SPACE_3 = 12
SPACE_4 = 16
SPACE_5 = 20
SPACE_6 = 24
SPACE_7 = 28
SPACE_8 = 36
SPACE_9 = 48

# Layout on the 1920 × 1080 reference screen; the window scales with the screen from there.
STAGE_WIDTH = 1920
STAGE_HEIGHT = 1080
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 830
HEADER_HEIGHT = 96
AVATAR_SIZE = 72
SIDEBAR_WIDTH = 340
ROW_LABEL_WIDTH = 330
ROW_VALUE_WIDTH = 120
DESC_MAX_WIDTH = 720
SCROLLBAR_WIDTH = 14
STATE_WIDTH = 48
SWITCH_WIDTH = 96
MASTER_WIDTH = 150
SLIDER_HEIGHT = 34
SLIDER_TRACK = 16
SLIDER_THUMB_WIDTH = 18
SLIDER_THUMB_HEIGHT = 34

# Kevin's themes (2026-10-06, docs/mokup/menu_mods/decisions.md): the colours above are EMBER, and each other theme
# lists the colours it changes. A theme changes colours only; shapes, fonts and sizes stay the menus' own.
THEMES = ("EMBER", "DARK", "LIGHT", "BL4")
# Kevin's window sizes (2026-10-06, decisions.md), in the order the header's button goes through them.
SIZES = ("LARGE", "FULL", "NORMAL")
PALETTES = {
    "EMBER": {},
    "DARK": {"COLOR_WINDOW": "16171b", "COLOR_HEADER": "1e2025", "COLOR_SIDEBAR": "101114", "COLOR_CARD": "0b0c0e",
             "COLOR_HOVER": "2a2d33", "COLOR_TRACK": "2a2d33", "COLOR_TEXT": "ececee", "COLOR_TEXT_DIM": "9a9ba3"},
    # An off button is filled with the card's cream, never left transparent: in game its frame is a whole box drawn
    # under the fill, so a transparent fill showed the frame's colour, which is the label's, and hid every label
    # (Kevin's screenshot, 2026-10-06). On a card it still reads as an outline, as in the mockup.
    "LIGHT": {"COLOR_WINDOW": "e8e2d6", "COLOR_HEADER": "d8cfbe", "COLOR_SIDEBAR": "ddd5c6", "COLOR_CARD": "f7f3eb",
              "COLOR_HOVER": "cbbfaa", "COLOR_TRACK": "cbbfaa", "COLOR_TEXT": "1b1612", "COLOR_TEXT_DIM": "66574a",
              "COLOR_OFF": "f7f3eb", "COLOR_GOLD_TEXT": "8a6400"},
    # Medians read from Kevin's two screenshots of the game's menus (docs/mokup/menu_mods/themes/reference_bl4_*).
    "BL4": {"COLOR_WINDOW": "042832", "COLOR_HEADER": "092429", "COLOR_SIDEBAR": "051d26", "COLOR_CARD": "041923",
            "COLOR_HOVER": "0d3340", "COLOR_TRACK": "13212b", "COLOR_SPARK": "fc850a", "COLOR_GOLD": "00c8f0",
            "COLOR_GOLD_HI": "7fe3ff", "COLOR_GOLD_SHADE": "00485c", "COLOR_TEXT": "b8c4c7", "COLOR_TEXT_DIM": "7f9196",
            "COLOR_INK": "000d19", "COLOR_OFF": "000d19", "COLOR_GOLD_TEXT": "00c8f0"},
}
_EMBER = {name: value for name, value in globals().items() if name.startswith("COLOR_")}

# Game-only values, not design tokens: the exporter skips names that start with an underscore or are listed here.
GAME_ONLY = ("ORDER", "SAVE_DELAY_NS", "PAGES", "BRAND", "AUTHOR", "PX_TO_POINTS", "SPARKS", "HOVER_OVERLAY",
             "PRESS_OVERLAY", "SELECTOR_WIDTH", "KEY_CHANGE_WIDTH", "FONT_LINE_HEIGHT", "GAME_ONLY", "THEMES",
             "PALETTES", "BACKDROP_BLUR", "SIZES")
ORDER = 10000
# The game behind an open window is blurred a little, as behind an app's pop-up (Kevin, 2026-10-06). Unreal's
# BackgroundBlur strength, which runs from 0 (sharp) to 100.
BACKDROP_BLUR = 6.0
SAVE_DELAY_NS = 300_000_000
PAGES = (*(group.identifier.removesuffix("_menu") for group in menu.MENU), "controls")
BRAND, AUTHOR = pack.NAME.upper(), "KEVIN-HDEV"
# Unreal sizes fonts in points drawn at 96 DPI: a size of 20 is 26.7 pixels. The mockup's pixels times 0.75 give
# the same letters; without it every text was a third larger than approved (screenshot of 2026-09-21).
PX_TO_POINTS = 0.75
# Line height of each shipped font, in em, read from the files' hhea tables (2026-09-21). Unreal always lays a line
# out at this height, where the mockup's CSS squeezes Anton to 1.15: panel_text trims the difference from paddings.
FONT_LINE_HEIGHT = {"title": 1.505, "body": 1.2}
# The key-capture buttons, absent from the mockup: wide enough for "2. CHOISIR LA DEUXIÈME TOUCHE".
SELECTOR_WIDTH = 420
# Movement's Change button beside a shortcut, absent from the mockup: its waiting text "APPUIE SUR UNE TOUCHE" measures
# 210 px in the button font (read from the font file, 2026-09-25); with margins and frame it keeps one width.
KEY_CHANGE_WIDTH = 248
KEY_ICON_SIZE = 40
# Movement's Options gear inside its KEY_ICON_SIZE button, sized like the mockup's (icon 70 %, teeth 22 % of it,
# ring and hub inset 14 % and 36 %).
GEAR_ICON_SIZE = 28
GEAR_TOOTH_WIDTH = 6
GEAR_RING_SIZE = 20
GEAR_HUB_SIZE = 8
# The mockup lightens a hovered button and darkens a pressed one; one veil does both for every button colour.
HOVER_OVERLAY = ("ffffff", 0.12)
PRESS_OVERLAY = ("000000", 0.2)
# The mockup's header sparks: (left, top, side, colour name, opacity), fixed so every opening looks the same.
SPARKS = (
    (300, 18, 5, "COLOR_SPARK", 0.9), (340, 62, 3, "COLOR_GOLD", 0.8), (420, 30, 4, "COLOR_SPARK", 0.6),
    (480, 70, 3, "COLOR_GOLD", 0.7), (560, 14, 3, "COLOR_SPARK", 0.5), (640, 52, 5, "COLOR_GOLD", 0.45),
    (720, 24, 3, "COLOR_SPARK", 0.4), (820, 66, 4, "COLOR_SPARK", 0.35), (900, 20, 3, "COLOR_GOLD", 0.3),
    (1000, 48, 3, "COLOR_SPARK", 0.25), (1120, 72, 4, "COLOR_GOLD", 0.25), (1180, 16, 3, "COLOR_SPARK", 0.3),
    (40, 78, 3, "COLOR_GOLD", 0.5), (120, 10, 4, "COLOR_SPARK", 0.6), (230, 80, 3, "COLOR_SPARK", 0.7),
)


_current = THEMES[0]


def use(theme):
    """Puts a theme's colours in place before a window is drawn; an unknown name draws EMBER.

    Every module reads the colours from here when it draws, never when the mod loads: a colour kept from loading
    would stay EMBER's in every theme (tables of colours hold their names, read through colour()).
    """
    global _current
    _current = theme if theme in PALETTES else THEMES[0]
    globals().update({**_EMBER, **PALETTES[_current]})


def current():
    """The theme the open window was drawn in."""
    return _current


def colour(name):
    """The current theme's colour for a role name such as "COLOR_GOLD"; None stays None, a transparent fill."""
    return None if name is None else globals()[name]


def luminance(hex_color):
    """How light a colour looks, from 0 for black to 1 for white (the WCAG formula, on the linear values)."""
    red, green, blue, _ = rgba(hex_color)
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def on_card(hex_color):
    """A content colour, such as a hunter's class, as text on a card: halved on a light card, where pale ones vanish."""
    if luminance(COLOR_CARD) < 0.5:
        return hex_color
    return "".join(f"{int(hex_color[index:index + 2], 16) // 2:02x}" for index in (0, 2, 4))


def rgba(hex_color, alpha=1.0):
    # Unreal colours are linear; converting from sRGB keeps the mockup's dark reds dark.
    values = tuple(int(hex_color[index:index + 2], 16) / 255 for index in (0, 2, 4))
    return tuple(value / 12.92 if value <= 0.04045 else ((value + 0.055) / 1.055) ** 2.4
                 for value in values) + (alpha,)


def points(pixels):
    return pixels * PX_TO_POINTS
