# Generated by sync_menu_ui; edit canonical sources.
"""The window's three sizes (Kevin, 2026-10-06, docs/mokup/menu_mods/decisions.md): more room, never larger text.

The ScaleBox fits the drawing into its share of the screen. Each size grows the drawing and its share together, so
the scale stays the 1920 × 1080 reference's: letters and buttons keep NORMAL's size, and the window still follows the
game's window when it is resized (seen in game on 2026-10-06).
"""

from . import panel_theme as t, panel_widgets as w

# LARGE is Kevin's red frame on his screenshot of 2026-10-06: 1705 × 979 of 1920 × 1080, shadow included.
_DRAWINGS = {"NORMAL": (t.WINDOW_WIDTH, t.WINDOW_HEIGHT), "LARGE": (1690, 965)}
# A screen's shape outside these is a misread, not a monitor: FULL then keeps the 16:9 drawing.
_ASPECTS = (4 / 3, 32 / 9)

_current = t.SIZES[0]
(WIDTH, HEIGHT), SHADOW = _DRAWINGS[_current], t.SHADOW_XL
STAGE_WIDTH, STAGE_HEIGHT = t.STAGE_WIDTH, t.STAGE_HEIGHT


def use(size, pc=None):
    """Sets the drawing before a window is drawn; an unknown name draws LARGE.

    FULL covers the whole screen, without the shadow that would leave a band on two of its sides. Its drawing takes
    the screen's shape, read from the player's controller pc, by growing the 1920 x 1080 reference on the long side
    only: wider on a 21:9 screen, taller on a 16:10 one, where a 16:9 drawing would leave bands or grow the letters.
    """
    global _current, WIDTH, HEIGHT, SHADOW, STAGE_WIDTH, STAGE_HEIGHT
    _current = size if size in t.SIZES else t.SIZES[0]
    STAGE_WIDTH, STAGE_HEIGHT = t.STAGE_WIDTH, t.STAGE_HEIGHT
    if _current != "FULL":
        (WIDTH, HEIGHT), SHADOW = _DRAWINGS[_current], t.SHADOW_XL
        return
    screen = None if pc is None else read_screen(pc)
    if screen is not None and _ASPECTS[0] <= screen[0] / screen[1] <= _ASPECTS[1]:
        aspect, reference = screen[0] / screen[1], t.STAGE_WIDTH / t.STAGE_HEIGHT
        if aspect >= reference:
            STAGE_WIDTH = round(t.STAGE_HEIGHT * aspect)
        else:
            STAGE_HEIGHT = round(t.STAGE_WIDTH / aspect)
    WIDTH, HEIGHT, SHADOW = STAGE_WIDTH, STAGE_HEIGHT, 0


def current():
    """The size the open window was drawn in."""
    return _current


def share():
    """The window's part of the screen, shadow included: (width, height), each from 0 to 1."""
    return (WIDTH + SHADOW) / STAGE_WIDTH, (HEIGHT + SHADOW) / STAGE_HEIGHT


def read_screen(pc):
    """The game's viewport in pixels, or None.

    A probe read (2560, 1440) with this call on 2026-09-26 (releves/third_person_fov/2026-09-26-drone-camera).
    """
    found = []
    if not w.cosmetic("viewport_size", lambda: found.append(pc.GetViewportSize(0, 0))):
        return None
    return pixels(found[0])


def pixels(value):
    """(width, height) from the shapes Unreal returns: the two last numbers of a tuple, or a struct's fields."""
    for names in (("SizeX", "SizeY"), ("X", "Y")):
        if all(hasattr(value, name) for name in names):
            value = tuple(getattr(value, name) for name in names)
            break
    if not isinstance(value, (tuple, list)):
        return None
    numbers = [item for item in value if isinstance(item, (int, float)) and not isinstance(item, bool)]
    if len(numbers) < 2 or not all(0 < number < 100_000 for number in numbers[-2:]):
        return None
    return float(numbers[-2]), float(numbers[-1])
