# Generated by sync_menu_ui; edit canonical sources.
"""Refresh texts and button states without rebuilding widgets or losing key capture state.

Selection shows as in the mockup: the chosen page and language become gold plates, never a "> " or "[EN]" mark.
"""

from . import menu, panel_buttons as b, panel_choices, panel_i18n as i18n, panel_slider as s
from . import panel_commands, panel_theme as t
from . import panel_theme_choice


def _buttons(form, widgets, language):
    for name in ("close", "restore", "undo"):
        widgets[f"{name}_label"].SetText(i18n.text(name, language))
    widgets["undo"].SetIsEnabled(form.model.can_undo)
    b.paint(widgets, "undo", "secondary" if form.model.can_undo else "disabled")
    panel_theme_choice.paint(widgets, form.model.theme, language)
    for lang in ("EN", "FR"):
        widgets[f"{lang}_label"].SetText(lang)
        b.paint(widgets, lang, "lang_on" if lang == language else "lang_off")
    for index, key in enumerate(t.PAGES):
        widgets[f"nav:{key}_label"].SetText(i18n.text(key, language))
        b.paint(widgets, f"nav:{key}", "nav_on" if form.page == index else "nav_off")
    enabled = form.model.mod.is_enabled
    widgets["enabled_label"].SetText(i18n.text("enabled" if enabled else "disabled", language))
    b.paint(widgets, "enabled", "on" if enabled else "off")


def apply(form, widgets):
    from . import __version__
    language = form.model.language
    _buttons(form, widgets, language)
    widgets["tag"].SetText(f"{i18n.text('by', language)} {t.AUTHOR}")
    widgets["settings_caption"].SetText(i18n.text("settings", language))
    widgets["meta"].SetText(f"{i18n.text('version', language)} {__version__} · {i18n.text('by', language)} {t.AUTHOR}")
    for group, key in zip(form.model.groups, t.PAGES):
        widgets[f"heading:{key}"].SetText(i18n.text(key, language))
        widgets[f"group:{key}"].SetText(i18n.group_text(group, key, language))
        if key in menu.NOTICES:
            widgets[f"notice:{key}"].SetText(i18n.text(menu.NOTICES[key], language).upper())
    for key, option in form.model.options.items():
        title, description = i18n.option_text(option, language)
        widgets[f"label:{key}"].SetText(title.upper())
        widgets[f"description:{key}"].SetText(description)
    widgets["notice"].SetText(i18n.text(form.notice, language))
    panel_commands.refresh(form, widgets, form.command_catalogue)


def value(widgets, option, current, language):
    key = option.identifier
    if type(option.default_value) is bool:
        widgets[f"setting:{key}_label"].SetText(i18n.text("on" if current else "off", language))
        b.paint(widgets, f"setting:{key}", "on" if current else "off")
    elif panel_choices.is_choice(option):
        panel_choices.paint(widgets, option, current, language)
    else:
        s.show(widgets, option, current)
