# Generated by sync_menu_ui; edit canonical sources.
"""Generic window messages generated from Apex Grapple.
"""

TEXT = {'close': 'FERMER',
 'restore': 'RÉGLAGES D’ORIGINE',
 'undo': 'ANNULER LE RESET',
 'enabled': 'ACTIVÉ',
 'disabled': 'DÉSACTIVÉ',
 'on': 'OUI',
 'off': 'NON',
 'by': 'PAR',
 'version': 'VERSION',
 'settings': 'RÉGLAGES',
 'ready': 'Sauvegarde automatique. Fermer revient à la liste des mods.',
 'saved': 'Enregistré.',
 'failed': 'Impossible d’enregistrer les réglages. Réessaie.',
 'toggle_failed': 'Impossible d’activer ou de désactiver le mod. Rien n’a changé. La raison est '
                  'dans unrealsdk.log.',
 'restored': 'Réglages d’origine restaurés. Tu peux annuler cette restauration.',
 'undone': 'Réglages précédents rétablis.',
 'refused': 'Attribution refusée. Cette touche est réservée ou déjà utilisée.',
 'rollback_abandoned': 'Changement annulé. Le rétablissement n’a pas été confirmé ; relance le jeu '
                       'avant de changer les réglages.',
 'theme': 'THÈME :',
 'theme:EMBER': 'BRAISE',
 'theme:DARK': 'SOMBRE',
 'theme:LIGHT': 'CLAIR',
 'theme:BL4': 'BL4',
 'theme_later': 'Thème enregistré. Il s’affichera à la prochaine ouverture du menu.',
 'window_size': 'FENÊTRE :',
 'window_size:LARGE': 'GRANDE',
 'window_size:FULL': 'PLEIN ÉCRAN',
 'window_size:NORMAL': 'NORMALE',
 'window_size_later': 'Taille de la fenêtre enregistrée. Elle s’affichera à la prochaine ouverture '
                      'du menu.'}
