# Generated by sync_menu_ui; edit canonical sources.
"""A close shares the pending operation's deadline and survives failed safety reads."""
import time

from .control_window_hooks import note


def abort(form):
    operation = getattr(form, "close_abort", None)
    try:
        if callable(operation):
            operation()
    except Exception as error:
        note(f"close_abort_error={type(error).__name__}")


def defer(session, reason):
    now = time.perf_counter_ns()
    try:
        invalid = not session.same_context(session.pc())
    except Exception as error:
        note(f"close_context_error={type(error).__name__}")
        invalid = True
    expired = session.close_deadline is not None and now >= session.close_deadline
    if invalid:
        abort(session.form)
    else:
        gate = getattr(session.form, "close_ready", None)
        try:
            if callable(gate) and not gate():
                if expired:
                    # The valid-context gate first gets a chance to expire and restore its transaction.
                    abort(session.form)
                    session.deferred_close = ""
                    return False
                if session.close_deadline is None:
                    deadline = getattr(session.form, "close_deadline", None)
                    session.close_deadline = deadline() if callable(deadline) else now
                session.deferred_close = reason
                return True
        except Exception as error:
            note(f"close_gate_error={type(error).__name__}")
            abort(session.form)
    session.deferred_close = ""
    return False
