# Generated by sync_menu_ui; edit canonical sources.
"""Escape closes the window as its Close button does, back to the mods list (Kevin: Save Editor on 2026-09-30,
validated in game; every menu of ours on 2026-10-06).

The key is read as Windows sees it, and the window closes one turn after it is released, never while it is down:
closed while it was down, the window reopened the console's mods list and handed the input back, and the Escape
reaching the game then closed the console and opened the pause menu (Save Editor's trial of 2026-09-30,
docs/candidats/editeur_de_sauvegarde/README.md).

Known limits: Windows reports the key whatever program has it, so an Escape pressed in another program while the
game runs behind also closes the window, which is harmless (closing loses nothing, as with the Close button); and
the PRESSED bit of a press shorter than a turn can be taken by another program's read.
"""

import ctypes
import os
from ctypes import wintypes

from .control_window_hooks import note

VK_ESCAPE = 0x1B
DOWN, PRESSED = 0x8000, 0x0001


def user32():
    if os.name != "nt":
        raise RuntimeError("Unsupported platform")
    api = ctypes.WinDLL("user32", use_last_error=True)
    api.GetAsyncKeyState.argtypes = [ctypes.c_int]
    api.GetAsyncKeyState.restype = wintypes.SHORT
    return api


class EscapeWatch:
    """Built when the window opens: an Escape pressed before it must not close it."""

    def __init__(self, api=None):
        self.api = api
        self.seen_down = self.closing = self.muted = self.busy = self.failed = False
        self._read()

    def _read(self):
        """The key's state, or 0 once it could not be read: the window then keeps only its Close button."""
        if self.failed:
            return 0
        try:
            if self.api is None:
                self.api = user32()
            return self.api.GetAsyncKeyState(VK_ESCAPE)
        except Exception as error:
            if not self.failed:
                self.failed = True
                note(f"escape_unreadable={type(error).__name__}")
            return 0

    def released(self, busy=False):
        """One read per call. True once, at the call after the one that saw the release; a new press during that
        turn waits for its own release.

        busy: a key is being chosen. Escape then cancels the choice in the key's field, and that press never closes
        the window, even when the field has already let go of the key at this turn (busy at the previous call)."""
        state = self._read()
        busy, self.busy = busy or self.busy, busy
        if busy or self.muted:
            self.muted = bool(state & DOWN)
            self.seen_down = self.closing = False
            return False
        if state & DOWN:
            self.seen_down, self.closing = True, False
            return False
        if self.closing:
            if state & PRESSED:
                return False
            self.closing = False
            note("escape_released=true")
            return True
        if self.seen_down or state & PRESSED:
            self.seen_down = False
            self.closing = True
        return False
