# Generated by sync_menu_ui; edit canonical sources.
"""The existing camera page gains three preset rows and the existing slider style."""
from . import camera_control_config as config, panel_buttons as b, panel_pages as p
from . import panel_framing_text as labels, panel_slider as s, panel_text as tx
from . import panel_theme as t, panel_widgets as w


def build(body, widgets, template, keys):
    for index, group in enumerate(config.FRAMING_GROUPS):
        if group.key not in keys:
            continue
        key = "framing:" + group.key
        option = config.FRAMING_OPTIONS.options[index * 2]
        rows = p.card(body, widgets, key)
        choices = w.new("HorizontalBox", rows)
        for preset, _choice in enumerate(group.presets):
            name = f"{key}:preset:{preset}"
            w.row(choices, b.button(choices, widgets, name, "lang", template, "off"),
                  padding=w.pad(0, t.SPACE_3, 0, 0))
        w.column(rows, choices, padding=w.pad(t.SPACE_3, 0, t.SPACE_3))
        line = w.new("HorizontalBox", rows)
        w.row(line, s.slider(line, widgets, option, template), fill=True,
              padding=w.pad(0, t.SPACE_4, 0, 0))
        w.row(line, s.value_box(line, widgets, option.identifier), valign="Center")
        w.column(rows, line, padding=w.pad(t.SPACE_2, 0, t.SPACE_3))


def show(widgets, group, option, choice, language, enabled, unavailable):
    key = "framing:" + group.key
    value, custom = choice
    title, description = labels.text(group.key, language)
    percent = f"{value:+d}" + (" %" if language == "FR" else "%")
    name = "Custom" if custom else next(label for label, number in group.presets if number == value)
    description += " " + labels.text(name, language) + f" ({percent})."
    if unavailable:
        reason = unavailable if unavailable in ("zoom_unavailable", "position_unavailable") else "unavailable"
        description += "\n" + labels.text(reason, language)
    widgets[f"heading:{key}"].SetText(title)
    widgets[f"group:{key}"].SetText(description)
    widgets[f"setting:{option.identifier}"].SetIsEnabled(enabled)
    widgets[f"setting:{option.identifier}"].SetRenderOpacity(1.0 if enabled else t.OPACITY_DISABLED)
    s.show(widgets, option, value)
    widgets[f"value:{option.identifier}"].SetText(percent)
    for index, (label, number) in enumerate(group.presets):
        name = f"{key}:preset:{index}"
        widgets[name].SetIsEnabled(enabled)
        widgets[name + "_label"].SetText(labels.text(label, language))
        b.paint(widgets, name, "disabled" if not enabled else "on" if not custom and number == value else "off")
