# Generated by sync_menu_ui; edit canonical sources.
"""Restore and Undo compose settings and commands under one shared deadline."""


class Restore:
    success_notice = "saved"

    def restore(self):
        memory = ()
        if self.command_actions is not None and not self.camera_elsewhere:
            from .camera_control_config import MEMORY_OPTIONS
            # The Orbit distance is a page setting here, not only a value remembered beside them.
            memory = tuple(option for option in MEMORY_OPTIONS if option.identifier not in self.options)
        previous = tuple((option, option.value) for option in (*self.options.values(), *memory)
                         if not self.camera_elsewhere or option.identifier not in self.camera_options)
        if not previous:
            return False
        commands = self.command_actions.snapshot() if self.command_actions else {}
        desired = self.command_actions.commands.defaults() if self.command_actions else {}
        return self._start_global(tuple((option, option.default_value) for option, _ in previous),
                                  "restore", previous, desired, commands)

    def undo(self):
        if not self._undo:
            return False
        changes = tuple((option, value) for option, value in self._undo
                        if not self.camera_elsewhere or (option.identifier in self.options
                                                        and option.identifier not in self.camera_options))
        if not changes:
            if self.camera_elsewhere:
                # Kevin chose a disclosed partial Undo; never replay the camera half later.
                self._undo, self._command_undo = (), {}
                self.success_notice = "undone_partial"
                return True
            return False
        previous = tuple((option, option.value) for option, _ in changes)
        commands = self.command_actions.snapshot() if self.command_actions else {}
        return self._start_global(changes, "undo", previous, self._command_undo, commands)

    def _start_global(self, changes, kind, previous, command_values, previous_commands):
        partial = (kind == "undo" and self.camera_elsewhere
                   and (len(changes) != len(self._undo) or bool(self._command_undo)))
        self.success_notice = "undone_partial" if partial else {"restore": "restored", "undo": "undone"}[kind]
        self._command_plan = (kind, previous, command_values, previous_commands, self._undo)
        def prepare_commands(restoring):
            if self.command_actions is None or not restoring and self.camera_elsewhere:
                return True
            values = previous_commands if restoring else command_values
            return self.command_actions.prepare(values, restoring=restoring)
        # One persistence call after both halves confirm; never save options before bindings.
        outcome = self.transaction.start(changes, previous, kind, finalize=prepare_commands)
        if outcome is None:
            return None
        return self._finish_global(outcome, label=False)

    def _finish_global(self, outcome, label):
        kind, previous, command_values, previous_commands, former_undo = self._command_plan
        success = self._complete(outcome)
        if success:
            if kind == "restore":
                self._command_undo = previous_commands
            elif kind == "undo":
                self._command_undo = {}
        else:
            self._undo = () if kind == "restore" else former_undo
        self._command_plan = None
        if not label:
            return success
        return self.success_notice if success else "failed"
