# Generated by sync_menu_ui; edit canonical sources.
"""Advance one ordered settings transaction, including asynchronous camera choices."""

import time

from . import panel_transaction_config as config
from .panel_transaction_config import TRANSACTION_TIMEOUT_NS
from .panel_transaction_recovery import Recovery
from . import panel_persistence


def write_options(model, values):
    """Validate one write and recheck live ownership immediately before persistence."""
    if type(values) is not dict or not 0 < len(values) <= len(model.options):
        return False
    if "third_person_ads" in model.options:
        from .panel_ads import refuses
        if refuses(values):
            return False
    try:
        changes = tuple((model.options[key], model.normalize(model.options[key], value))
                        for key, value in values.items())
    except (KeyError, TypeError, ValueError, OverflowError):
        return False
    return model.save(changes, "write")


def _priority(change):
    option, target = change
    if option.identifier == "third_person":
        return 0 if target is True else 4
    if option.identifier == "orbit":
        # Leave Orbit before restoring its locked entry view.
        return -1 if target is False else 3
    return 2


class Transaction(Recovery):
    def __init__(self, mod, report, clock=time.perf_counter_ns):
        self.mod = mod
        self.report = report
        self.clock = clock
        self.changes = ()
        self.previous = ()
        self.kind = ""
        self.index = 0
        self.waiting = False
        self.waiting_since = 0
        self.rolling_back = False
        self.confirm_since = 0
        self.retry_after = 0
        self.rollback_failures = 0
        self.rollback_deadline = 0
        self.started = 0
        self.deadline = 0
        self.failure_reason = "failed"
        self.finalize = None
        self.persist_rollback = True
        self.restoration_confirmed = False

    @property
    def pending(self):
        return bool(self.kind)

    @staticmethod
    def _ordered(changes):
        return tuple(sorted(changes, key=_priority))

    def start(self, changes, previous, kind, *, finalize=None):
        if self.pending:
            return None
        self.changes = self._ordered(changes)
        self.previous = tuple(previous)
        self.kind = kind
        self.index = 0
        self.waiting = False
        self.waiting_since = 0
        self.rolling_back = False
        self.confirm_since = 0
        self.retry_after = 0
        self.rollback_failures = 0
        self.rollback_deadline = 0
        self.started = self.clock()
        self.deadline = self.started + config.TRANSACTION_TOTAL_TIMEOUT_NS
        self.failure_reason = "failed"
        self.finalize = finalize
        self.persist_rollback = True
        self.restoration_confirmed = False
        self.persistence_failed = False
        # Runtime saves can occur while a camera request waits; compare to the original file.
        self.original_fingerprint = panel_persistence.fingerprint(self.mod, self.report)
        return self._run()

    def advance(self):
        if not self.pending:
            return None
        return self._run()

    def cancel(self):
        if not self.pending:
            return None
        if self._expired():
            return self._abandon_rollback()
        if self.rolling_back:
            return self._run()
        if self.waiting:
            option, _target = self.changes[self.index]
            status = getattr(option, "camera_status", "refused")
            if status in ("pending", "waiting") and not self._cancel_current(option):
                return None
        return self._fail()

    def _run(self):
        if self._expired() or self.rolling_back and self.clock() >= self.rollback_deadline:
            return self._abandon_rollback()
        if self.clock() < self.retry_after:
            return None
        if self.waiting:
            option, target = self.changes[self.index]
            if option.value == target and getattr(option, "camera_status", "confirmed") not in ("pending", "waiting"):
                self.waiting = False
                self.waiting_since = 0
                self.index += 1
            elif getattr(option, "camera_status", "refused") in ("pending", "waiting"):
                status = option.camera_status
                if not self._pause():
                    if not self.rolling_back:
                        self.failure_reason = "camera_timeout"
                    return self._fail() if self._cancel_current(option) else None
                if status == "pending":
                    return None
                self.waiting = False
            else:
                self.failure_reason = "camera_refused"
                return self._fail()
        while self.index < len(self.changes):
            option, target = self.changes[self.index]
            if option.value == target:
                if getattr(option, "camera_status", "confirmed") in ("pending", "waiting"):
                    if not self._pause():
                        if not self.rolling_back:
                            self.failure_reason = "camera_timeout"
                        return self._fail() if self._cancel_current(option) else None
                    return None
                self.index += 1
                continue
            try:
                option.value = target
            except Exception:
                return self._fail()
            if hasattr(option, "camera_status") and option.value != target:
                if option.camera_status in ("pending", "waiting"):
                    if not self._pause():
                        if not self.rolling_back:
                            self.failure_reason = "camera_timeout"
                        return self._fail() if self._cancel_current(option) else None
                    return None
                self.failure_reason = "camera_refused"
                return self._fail()
            self.index += 1
        try:
            confirmations = tuple(option.confirm_write(restoring=self.rolling_back)
                                  for option, _ in self.changes
                                  if callable(getattr(option, "confirm_write", None)))
        except Exception:
            return self._fail()
        if any(answer is False for answer in confirmations):
            self.failure_reason = "camera_refused"
            self.report("panel:native", config.NATIVE_FAILURE)
            return self._fail()
        if any(answer is not True for answer in confirmations):
            now = self.clock()
            if not self.confirm_since:
                self.confirm_since = now
            if now - self.confirm_since > TRANSACTION_TIMEOUT_NS:
                if not self.rolling_back:
                    self.failure_reason = "camera_timeout"
                return self._fail()
            return None
        try:
            if self.finalize is not None and self.finalize(self.rolling_back) is not True:
                return self._fail()
            if self.rolling_back:
                self.restoration_confirmed = True
            if not self.rolling_back or self.persist_rollback:
                self.mod.save_settings()
        except Exception:
            if not self.rolling_back:
                self.failure_reason = "failed"
                self.persist_rollback = not panel_persistence.unchanged(
                    self.mod, self.original_fingerprint, self.report)
            else:
                self.persistence_failed = True
            self.report("panel:persistence", config.SAVE_FAILURE)
            return self._fail()
        self.persistence_failed = False
        return self._finish(not self.rolling_back)

    def _pause(self):
        now = self.clock()
        if not self.waiting_since:
            self.waiting_since = now
        elif now - self.waiting_since > TRANSACTION_TIMEOUT_NS:
            return False
        self.waiting = True
        return True

    @staticmethod
    def _cancel_current(option, restore=True):
        cancel = getattr(option, "cancel_pending", None)
        return bool(callable(cancel) and (cancel() if restore else cancel(restore=False)))

    def _finish(self, success):
        outcome = self.kind, self.previous, success
        self.changes = ()
        self.previous = ()
        self.kind = ""
        self.index = 0
        self.waiting = False
        self.waiting_since = 0
        self.rolling_back = False
        self.finalize = None
        return outcome
