# Generated by sync_menu_ui; edit canonical sources.
"""Refresh the same button colours and text roles used by Grapple's window."""

from . import panel_camera_pages as pages
from . import panel_buttons as b, panel_i18n as i18n, panel_shortcut as sc, panel_slider as s, panel_theme as t
from . import panel_theme_choice
from . import panel_size_choice


def apply(form, widgets):
    from . import __version__
    language = form.model.language
    for name in ("close", "restore", "undo"):
        widgets[f"{name}_label"].SetText(i18n.text(name, language))
    available = any(key not in form.model.camera_options for key in form.model.options) or not form.model.camera_elsewhere
    widgets["restore"].SetIsEnabled(available)
    b.paint(widgets, "restore", "secondary" if available else "disabled")
    widgets["undo"].SetIsEnabled(available and form.model.can_undo)
    b.paint(widgets, "undo", "secondary" if available and form.model.can_undo else "disabled")
    panel_size_choice.paint(widgets, form.model.window_size, language)
    panel_theme_choice.paint(widgets, form.model.theme, language)
    for lang in ("EN", "FR"):
        widgets[f"{lang}_label"].SetText(lang)
        b.paint(widgets, lang, "lang_on" if lang == language else "lang_off")
    for index, key in enumerate(form.model.pages):
        widgets[f"nav:{key}_label"].SetText(i18n.text(key, language))
        b.paint(widgets, f"nav:{key}", "nav_on" if form.page == index else "nav_off")
    enabled = form.model.mod.is_enabled
    widgets["enabled_label"].SetText(i18n.text("enabled" if enabled else "disabled", language))
    b.paint(widgets, "enabled", "on" if enabled else "off")
    widgets["tag"].SetText(f"{i18n.text('by', language)} {t.AUTHOR}")
    widgets["settings_caption"].SetText(i18n.text("settings", language))
    widgets["meta"].SetText(f"{i18n.text('version', language)} {__version__} · "
                            f"{i18n.text('by', language)} {t.AUTHOR}")
    for group, key in zip(form.model.groups, form.model.pages):
        widgets[f"heading:{key}"].SetText(i18n.text(key, language))
        elsewhere = form.model.camera_elsewhere and key in pages.PAGES
        from . import camera
        notice = "camera_outdated" if camera.framing_status() == "camera_outdated" else "camera_elsewhere"
        widgets[f"group:{key}"].SetText(i18n.text(notice, language) if elsewhere
                                        else pages.description(form, group, key, language))
    if "heading:command_external" in widgets:
        widgets["heading:command_external"].SetText(i18n.text("commands", language))
        widgets["group:command_external"].SetText(i18n.text("camera_elsewhere", language))
    for key, option in form.model.options.items():
        if sc.is_shortcut(option):
            sc.texts(widgets, key, language)
            continue
        title, description = i18n.option_text(option, language)
        widgets[f"label:{key}"].SetText(title.upper())
        widgets[f"description:{key}"].SetText(description)
    widgets["notice"].SetText(i18n.text(form.notice, language))


def value(widgets, option, current, language):
    key = option.identifier
    if sc.is_shortcut(option):
        sc.show_key(widgets[f"key:{key}"], current)
    elif key == "third_person_ads":
        label = (i18n.text("aim_third" if current else "aim_first", language) if language == "FR"
                 else option.true_text if current else option.false_text)
        widgets[f"setting:{key}_label"].SetText(label)
        b.paint(widgets, f"setting:{key}", "on" if current else "off")
    elif key == "shoulder_left":
        widgets[f"setting:{key}_label"].SetText(i18n.text("left" if current else "right", language))
        b.paint(widgets, f"setting:{key}", "on" if current else "off")
    elif type(option.default_value) is bool:
        widgets[f"setting:{key}_label"].SetText(i18n.text("on" if current else "off", language))
        b.paint(widgets, f"setting:{key}", "on" if current else "off")
    else:
        s.show(widgets, option, current)
        pages.show_unit(widgets, option, current, language)
