# Generated by sync_menu_ui; edit canonical sources.
"""The camera settings over the sidebar pages (Kevin, 2026-10-06): what each page holds and shows. The CAMERA
group also holds SHOULDER VIEW's settings, shown on their own page (panel_camera_tabs.py, Kevin, 2026-10-07)."""

from mods_base import NestedOption

from .panel_camera_text import EN

# DYNAMIC CAMERA last: a page index saved before it still names the same page.
# SENSITIVITY after it for the same reason (Kevin, 2026-10-08: its own page, after DYNAMIC CAMERA).
# OMNI DIRECTION after them all for the same reason (Kevin, 2026-10-09); menu.py shows it after the mod's main page.
PAGES = ("camera", "aiming", "orbit_camera", "loot", "dynamic_camera", "sensitivity", "omni_direction")
# Spacing and height shape the view on foot as well as aiming, so they stay on CAMERA; the zoom is aiming only.
FRAMING = {"camera": ("horizontal", "height"), "aiming": ("zoom",)}
# Orbit also works from first person; aiming, its speeds and the body's orientation need the third-person switch, and
# their page says so (OMNI DIRECTION greyed without a word: Kevin, 2026-10-09).
NEEDS_THIRD_PERSON = ("aiming", "sensitivity", "omni_direction")
# Engine units are centimetres; the Orbit distance reads in metres.
METRES = ("orbit_distance",)


def page_texts(texts):
    return {key: texts[f"{key}_page"] for key in PAGES}


def groups(settings, fov):
    """Presentation groups only: the SDK never registers them, so saved settings keep their flat identifiers."""
    shoulder = settings.shoulder_transition
    contents = ([settings.third_person, *fov, *settings.distance.options, shoulder.orbit_smooth, shoulder.duration, *settings.free_look.options,
                 settings.shoulder_left, *shoulder.automatic.options, shoulder.smooth],
                [settings.third_person_ads, *settings.optics.options],
                [settings.orbit, settings.zoom.option], list(settings.loot.options),
                [*settings.speed_fov.options, *settings.dynamic.options], list(settings.sensitivity.options),
                list(settings.omni.options))
    descriptions = page_texts(EN)
    return tuple(NestedOption(f"{key}_menu", options, display_name=EN[key].title(), description=descriptions[key])
                 for key, options in zip(PAGES, contents))


def build(rows, key, group, widgets, template):
    from . import panel_ownership, panel_shortcut as sc
    if key in PAGES:
        # One section per page: another camera mod's ownership hides every camera setting.
        rows = panel_ownership.section(rows, widgets, f"{key}:settings")
    if key == "dynamic_camera":
        from . import panel_dynamic
        panel_dynamic.build(rows, group.children, widgets, template)
    elif key == "omni_direction":
        from . import panel_omni_direction
        panel_omni_direction.build(rows, group.children, widgets, template)
    elif key == "sensitivity":
        from . import panel_weapon_sensitivity as weapons
        options, weapon_rows = weapons.split(group.children)
        sc.rows(rows, options, widgets, template)
        weapons.build(rows, weapon_rows, widgets, template)
    else:
        from . import panel_optics
        from .settings import SHOULDER_PAGE
        options, optics = panel_optics.split(option for option in group.children
                                             if option.identifier not in SHOULDER_PAGE)
        sc.rows(rows, options, widgets, template)
        if optics:
            panel_optics.build(rows, optics, widgets, template)
    if key in FRAMING:
        from . import panel_framing
        panel_framing.build(rows, widgets, template, FRAMING[key])


def description(form, group, key, language):
    from . import panel_i18n as i18n
    text = i18n.group_text(group, key, language)
    if key in NEEDS_THIRD_PERSON and form.shown.get("third_person") is not True:
        text += "\n" + i18n.text("third_person_needed", language)
    return text


def refresh(widgets, key, language):
    if key == "dynamic_camera":
        from . import panel_dynamic
        panel_dynamic.refresh(widgets, language)


def metres(centimetres, language):
    text = f"{centimetres / 100:.2f}".rstrip("0").rstrip(".")
    return (text.replace(".", ",") if language == "FR" else text) + " m"


def show_unit(widgets, option, value, language):
    key = option.identifier
    if key in METRES:
        for name, number in (("value", value), ("low", option.min_value), ("high", option.max_value)):
            widgets[f"{name}:{key}"].SetText(metres(number, language))
