# Generated by sync_menu_ui; edit canonical sources.
"""Validated settings transactions; Hunter Change's SDK options are the authority."""

import math

from . import menu, panel_preferences as prefs, report
from . import panel_toggle
from .panel_transaction import Transaction, write_options
from .panel_restore import Restore


class Model(Restore):
    # The line the window shows when the ENABLED switch did not take.
    toggle_notice = panel_toggle.FAILED

    def __init__(self, mod):
        self.mod = mod
        self.groups = tuple(menu.MENU)
        self.pages = tuple(group.identifier.removesuffix("_menu") for group in self.groups)
        self.options = {option.identifier: option for group in self.groups for option in group.children}
        self._undo = ()
        self._restore_plan = None
        self.transaction = Transaction(mod, report.error_once)

    @property
    def language(self):
        return "FR" if prefs.french.value is True else "EN"

    @property
    def page(self):
        index = prefs.last_page.value
        valid = (type(index) in (int, float) and math.isfinite(index) and int(index) == index
                 and 0 <= index < len(prefs.PAGE_KEYS))
        saved = prefs.PAGE_KEYS[int(index)] if valid else None
        return saved if saved in self.pages else self.pages[0]

    @property
    def can_undo(self):
        return bool(self._undo)

    @property
    def controller_icons(self):
        return prefs.controller_icons.value

    def save(self, changes, kind="save", previous=None):
        snapshot = (tuple((option, option.value) for option, _ in changes)
                    if previous is None else tuple(previous))
        return self._complete(self.transaction.start(changes, snapshot, kind))

    def _complete(self, outcome):
        if outcome is None:
            return None
        kind, previous, success = outcome
        if success and kind == "restore":
            self._undo = previous
        elif success and kind in ("write", "undo"):
            self._undo = ()
        return success

    def advance(self):
        outcome = self.transaction.advance()
        if outcome is None:
            return None
        if self._restore_plan is not None:
            return self._finish_global(outcome, label=True)
        kind = outcome[0]
        success = self._complete(outcome)
        return {"restore": "restored", "undo": "undone", "write": "saved"}.get(
            kind, "saved") if success else "failed"

    def cancel_transaction(self):
        if not self.transaction.pending:
            return True
        outcome = self.transaction.cancel()
        if outcome is None:
            return False
        self._complete(outcome)
        return True

    def change_language(self, value):
        return value in prefs.LANGUAGES and self.save(((prefs.french, value == "FR"),))

    @property
    def theme(self):
        return prefs.theme.value if prefs.theme.value in prefs.THEMES else prefs.theme.default_value

    def change_theme(self, value):
        return value in prefs.THEMES and self.save(((prefs.theme, value),))

    @property
    def window_size(self):
        size = prefs.window_size
        return size.value if size.value in prefs.SIZES else size.default_value

    def change_window_size(self, value):
        return value in prefs.SIZES and self.save(((prefs.window_size, value),))

    def change_controller_icons(self, value):
        return value in prefs.CONTROLLER_ICONS and self.save(((prefs.controller_icons, value),))

    def change_page(self, value):
        if type(value) is not str or value not in self.pages:
            return False
        wanted = prefs.PAGE_KEYS.index(value)
        return wanted == prefs.last_page.value or self.save(((prefs.last_page, wanted),))

    @staticmethod
    def normalize(option, value):
        if type(option.default_value) is bool:
            if type(value) is not bool:
                raise ValueError("Invalid switch")
            return value
        if type(value) not in (int, float) or not math.isfinite(value):
            raise ValueError("Invalid number")
        if not option.min_value <= value <= option.max_value:
            raise ValueError("Out of bounds")
        steps = round((value - option.min_value) / option.step)
        result = min(option.max_value, max(option.min_value, option.min_value + steps * option.step))
        return int(round(result)) if option.is_integer else round(result, 6)

    def write(self, values):
        return write_options(self, values)

    def toggle_enabled(self):
        if self.transaction.pending:
            return None
        previous = self.mod.is_enabled
        try:
            (self.mod.disable if previous else self.mod.enable)()
            self.mod.save_settings()
        except Exception as error:
            self.toggle_notice = panel_toggle.notice(not previous, error)
            try:
                (self.mod.enable if previous else self.mod.disable)()
                self.mod.save_settings()
            except Exception:
                report.error_once("panel:enable", "Could not restore the mod state. Please retry.")
            return False
        return self.mod.is_enabled != previous
