# Generated by sync_menu_ui; edit canonical sources.
"""Refresh the same button colours and text roles used by Grapple's window."""

from . import panel_buttons as b, panel_hunters as hunter_page, panel_i18n as i18n, panel_slider as s, panel_switch, panel_theme as t
from . import panel_theme_choice
from . import panel_size_choice


def apply(form, widgets):
    from . import __version__
    language = form.model.language
    for name in ("close",):
        widgets[f"{name}_label"].SetText(i18n.text(name, language))
    panel_size_choice.paint(widgets, form.model.window_size, language)
    panel_theme_choice.paint(widgets, form.model.theme, language)
    for lang in ("EN", "FR"):
        widgets[f"{lang}_label"].SetText(lang)
        b.paint(widgets, lang, "lang_on" if lang == language else "lang_off")
    for index, key in enumerate(form.model.pages):
        widgets[f"nav:{key}_label"].SetText(i18n.text(key, language))
        b.paint(widgets, f"nav:{key}", "nav_on" if form.page == index else "nav_off")
    enabled = form.model.mod.is_enabled
    widgets["enabled_label"].SetText(i18n.text("enabled" if enabled else "disabled", language))
    b.paint(widgets, "enabled", "on" if enabled else "off")
    widgets["tag"].SetText(f"{i18n.text('by', language)} {t.AUTHOR}")
    widgets["settings_caption"].SetText(i18n.text("settings", language))
    widgets["meta"].SetText(f"{i18n.text('version', language)} {__version__} · "
                            f"{i18n.text('by', language)} {t.AUTHOR}")
    for group, key in zip(form.model.groups, form.model.pages):
        widgets[f"heading:{key}"].SetText(i18n.text(key, language))
        widgets[f"group:{key}"].SetText(i18n.group_text(group, key, language))
    for key, option in form.model.options.items():
        title, description = i18n.option_text(option, language)
        widgets[f"label:{key}"].SetText(title.upper())
        widgets[f"description:{key}"].SetText(description)
    hunter_page.paint(widgets, form.hunter_state, language, form.model.mod.is_enabled)
    panel_switch.paint(widgets, form.switch_page.view, language)
    widgets["notice"].SetText(i18n.text(form.notice, language))


def value(widgets, option, current, language):
    key = option.identifier
    if type(option.default_value) is bool:
        widgets[f"setting:{key}_label"].SetText(i18n.text("on" if current else "off", language))
        b.paint(widgets, f"setting:{key}", "on" if current else "off")
    else:
        s.show(widgets, option, current)
