# Generated by sync_menu_ui; edit canonical sources.
"""The CAMERA page's two halves, CAMERA VIEW and SHOULDER VIEW, each with the same two buttons at its head."""

from . import panel_buttons as b, panel_i18n as i18n, panel_pages as p
from . import panel_shortcut as sc, panel_theme as t, panel_widgets as w
from .settings import SHOULDER_PAGE

CAMERA, SHOULDER = "camera", "shoulder"
TABS = (CAMERA, SHOULDER)
NAMES = {CAMERA: "camera_view", SHOULDER: "shoulder_view"}


def frame(owner, widgets, template, page):
    """The two buttons stay above the card, in reach while the settings scroll under them."""
    column = w.new("VerticalBox", owner)
    line = w.new("HorizontalBox", column)
    for index, tab in enumerate(TABS):
        w.row(line, b.button(line, widgets, f"tab:{page}:{tab}", "tab", template, "off"),
              padding=w.pad(0, 0, 0, 0 if index == 0 else t.SPACE_3), valign="Center")
    w.column(column, line, padding=w.pad(t.SPACE_7, t.SPACE_8, t.SPACE_5))
    scroll, body = p.scrolling_body(column, template, top=0)
    w.column(column, scroll, fill=True)
    return column, body


def shoulder_page(owner, model, widgets, template):
    from . import panel_ownership  # Through panel_labels, which reads this module: imported once the window is built.
    page, body = frame(owner, widgets, template, SHOULDER)
    rows = panel_ownership.section(p.card(body, widgets, SHOULDER), widgets, f"{SHOULDER}:settings")
    sc.rows(rows, [model.options[key] for key in SHOULDER_PAGE], widgets, template)
    return page


def hidden(page):
    """SHOULDER VIEW is reached from CAMERA's head, not from the sidebar."""
    return page == SHOULDER


def lit(form, key, index):
    """CAMERA's sidebar button stays lit on either half."""
    return form.page == index or (key == CAMERA and form.model.pages[form.page] == SHOULDER)


def poll(form, widgets):
    for page in TABS:
        for tab in TABS:
            if form.take(widgets[f"tab:{page}:{tab}"]):
                if form.flush(widgets) and form.model.change_page(tab):
                    form.page = form.model.pages.index(tab)
                    widgets["pages"].SetActiveWidgetIndex(form.page)
                    form.refresh_labels(widgets)
                else:
                    form.report(widgets, "failed")
                return True
    return False


def refresh(form, widgets, language):
    shown = form.model.pages[form.page]
    for page in TABS:
        for tab in TABS:
            name = f"tab:{page}:{tab}"
            widgets[f"{name}_label"].SetText(i18n.text(NAMES[tab], language))
            b.paint(widgets, name, "on" if tab == shown else "off")
    widgets[f"heading:{SHOULDER}"].SetText(i18n.text(NAMES[SHOULDER], language))
    from . import camera
    notice = "camera_outdated" if camera.framing_status() == "camera_outdated" else "camera_elsewhere"
    widgets[f"group:{SHOULDER}"].SetText(i18n.text(notice if form.model.camera_elsewhere else "shoulder_desc",
                                                   language))
