# Generated by sync_menu_ui; edit canonical sources.
"""Validated settings transactions; Third Person & FOV's SDK options are the authority."""

import math

from mods_base import KeybindOption

from . import camera, menu, panel_preferences as prefs, report, settings
from . import panel_toggle
from .panel_transaction import Transaction, write_options
from .panel_restore import Restore


class Model(Restore):
    # The line the window shows when the ENABLED switch did not take.
    toggle_notice = panel_toggle.FAILED

    def __init__(self, mod):
        self.mod = mod
        self.groups = tuple(menu.MENU)
        self.pages = tuple(group.identifier.removesuffix("_menu") for group in self.groups)
        # While another higher-priority camera mod is on, these settings would change nothing.
        # The page then shows where to set the camera instead (Kevin, 2026-09-25).
        self.camera_options = {option.identifier: option for option in menu.camera.children}
        self.options = {option.identifier: option for group in self.groups for option in group.children}
        self.command_options = {option.identifier: option for option in settings.commands.options}
        from .camera_control_actions import Actions
        self.command_actions = Actions(settings.commands, mod)
        self.pages += ("commands",)
        self._undo, self._command_undo = (), {}
        self._command_plan = None
        self.transaction = Transaction(mod, report.error_once)

    @property
    def camera_elsewhere(self):
        if not self.camera_options:
            return False
        from . import camera
        return camera.elected_elsewhere()

    @property
    def language(self):
        return "FR" if prefs.french.value is True else "EN"

    @property
    def page(self):
        index = prefs.last_page.value
        valid = (type(index) in (int, float) and math.isfinite(index) and int(index) == index
                 and 0 <= index < len(prefs.PAGE_KEYS))
        saved = prefs.PAGE_KEYS[int(index)] if valid else None
        return saved if saved in self.pages else self.pages[0]

    @property
    def can_undo(self):
        return bool(self._undo)

    @property
    def controller_icons(self):
        return prefs.controller_icons.value

    def save(self, changes, kind="save", previous=None):
        snapshot = (tuple((option, option.value) for option, _ in changes)
                    if previous is None else tuple(previous))
        return self._complete(self.transaction.start(changes, snapshot, kind))

    def _complete(self, outcome):
        if outcome is None:
            return None
        kind, previous, success = outcome
        if success and kind == "restore":
            self._undo = previous
        elif success and kind in ("write", "undo"):
            self._undo = ()
        return success

    def advance(self):
        outcome = self.transaction.advance()
        if outcome is None:
            return None
        if self._command_plan is not None:
            return self._finish_global(outcome, label=True)
        kind = outcome[0]
        success = self._complete(outcome)
        return {"restore": "restored", "undo": "undone", "write": "saved"}.get(
            kind, "saved") if success else "failed"

    def cancel_transaction(self):
        if not self.transaction.pending:
            return True
        outcome = self.transaction.cancel()
        if outcome is None:
            return False
        self._complete(outcome)
        return True

    def change_language(self, value):
        return value in prefs.LANGUAGES and self.save(((prefs.french, value == "FR"),))

    def change_controller_icons(self, value):
        return value in prefs.CONTROLLER_ICONS and self.save(((prefs.controller_icons, value),))

    def change_page(self, value):
        if type(value) is not str or value not in self.pages:
            return False
        wanted = prefs.PAGE_KEYS.index(value)
        return wanted == prefs.last_page.value or self.save(((prefs.last_page, wanted),))

    @staticmethod
    def normalize(option, value):
        if isinstance(option, KeybindOption):
            raise ValueError("Shortcuts belong to the commands page")
        if type(option.default_value) is bool:
            if type(value) is not bool:
                raise ValueError("Invalid switch")
            return value
        if type(value) not in (int, float) or not math.isfinite(value):
            raise ValueError("Invalid number")
        if not option.min_value <= value <= option.max_value:
            raise ValueError("Out of bounds")
        steps = round((value - option.min_value) / option.step)
        result = min(option.max_value, max(option.min_value, option.min_value + steps * option.step))
        return int(round(result)) if option.is_integer else round(result, 6)

    def write(self, values):
        if (self.camera_elsewhere and type(values) is dict
                and any(key in self.camera_options for key in values)):
            return False
        return write_options(self, values)

    def write_commands(self, values):
        if not self._commands_ready():
            return False
        success = self.command_actions.apply(values)
        if success:
            self._undo, self._command_undo = (), {}
        return success

    def assign_command(self, action, device, key):
        if not self._commands_ready():
            return False
        success = self.command_actions.assign(action, device, key)
        if success:
            self._undo, self._command_undo = (), {}
        return success

    def default_commands(self):
        if not self._commands_ready():
            return False
        success = self.command_actions.defaults()
        if success:
            self._undo, self._command_undo = (), {}
        return success

    def _commands_ready(self):
        return (not self.camera_elsewhere and self.command_actions is not None and not self.transaction.pending
                and self._command_plan is None)

    def toggle_enabled(self):
        if self.transaction.pending:
            return None
        previous = self.mod.is_enabled
        try:
            (self.mod.disable if previous else self.mod.enable)()
            if not previous:
                refusal = camera.start()
                if refusal is not None:
                    raise refusal
            self.mod.save_settings()
        except Exception as error:
            self.toggle_notice = panel_toggle.notice(not previous, error)
            try:
                (self.mod.enable if previous else self.mod.disable)()
                self.mod.save_settings()
            except Exception:
                report.error_once("panel:enable", "Could not restore the mod state. Please retry.")
            return False
        return self.mod.is_enabled != previous
