# Generated by sync_menu_ui; edit canonical sources.
"""Keep one widget tree while camera ownership changes; inactive controls stay hidden."""

from . import panel_widgets as w
from .panel_camera_ownership import refresh


def section(parent, widgets, name):
    body = w.new("VerticalBox", parent)
    widgets[name] = body
    w.column(parent, body)
    return body
