# Generated by sync_menu_ui; edit canonical sources.
"""Where the open page was scrolled: kept when the window closes, after a theme change and across restarts.

Kevin, 2026-10-06: the window already reopens on its last page, but always at the top; a player tuning a setting
over a hundred tries had to scroll back down each time. The menu reopens as it was left, the game restarted or not.
Only the page shown at closing keeps its place: the window reopens on that page.
"""

import math

from mods_base import SliderOption

from .control_window_hooks import note

MAX_OFFSET = 100_000
last_scroll = SliderOption("menu_last_scroll", 0, 0, MAX_OFFSET, step=1, is_integer=True, is_hidden=True)
# The page is laid out over its first frames: the offset is set again for this many polls (50 ms each) before it is
# read back. A page shorter than the offset shows its end.
SETTLE_POLLS = 4
# The shown page's scroll box sits a few containers down (a head kept above it on Apex Movement's Options).
MAX_DEPTH = 6
MAX_WIDGETS = 64


def page_scroll(widgets):
    """The first scroll box under the page on screen, or None."""
    pending = [(widgets["pages"].GetActiveWidget(), 0)]
    seen = 0
    while pending and seen < MAX_WIDGETS:
        widget, depth = pending.pop(0)
        seen += 1
        if widget is None:
            continue
        if str(widget.Class.Name) == "ScrollBox":
            return widget
        if depth >= MAX_DEPTH:
            continue
        try:
            count = int(widget.GetChildrenCount())
        except AttributeError:
            continue  # Not a container: a text, an image, a button's label.
        pending.extend((widget.GetChildAt(index), depth + 1) for index in range(min(count, MAX_WIDGETS)))
    return None


def saved():
    value = last_scroll.value
    return int(value) if type(value) in (int, float) and math.isfinite(value) and 0 <= value <= MAX_OFFSET else 0


def offset(widgets):
    """The shown page's scroll, in whole pixels, or None when it cannot be read."""
    scroll = page_scroll(widgets)
    value = float(scroll.GetScrollOffset()) if scroll is not None else math.nan
    return min(MAX_OFFSET, max(0, round(value))) if math.isfinite(value) else None


class Memory:
    def __init__(self, model, wanted=None):
        self.model = model
        self.wanted = saved() if wanted is None else wanted
        self.polls = 0
        self.done = self.wanted == 0

    def restore(self, widgets):
        """Called at each poll until the offset is placed; a failure leaves the page at the top, never the window."""
        if self.done:
            return
        try:
            scroll = page_scroll(widgets)
            if scroll is None:
                self._finish("scroll_restore=no_scroll")
                return
            self.polls += 1
            if self.polls <= SETTLE_POLLS:
                scroll.SetScrollOffset(float(self.wanted))
                return
            self._finish(f"scroll_restored wanted={self.wanted} shown={float(scroll.GetScrollOffset()):.0f}")
        except Exception as error:
            self._finish(f"scroll_restore_error={type(error).__name__}")

    def _finish(self, line):
        self.done = True
        note(line)

    def remember(self, widgets):
        """At closing. Not before the offset was placed: a window closed at once would save the top instead."""
        if not self.done:
            return
        try:
            value = offset(widgets)
            # Apex Movement's save answers None while its write is still under way: only False is a failure.
            if value is not None and value != saved() and self.model.save(((last_scroll, value),)) is False:
                note("scroll_save=failed")
        except Exception as error:
            note(f"scroll_save_error={type(error).__name__}")
