"""Camera texts generated from Apex Movement's menu, whose Options page shows the same settings.
"""

EN = {'camera': 'CAMERA',
 'camera_desc': 'View, field of view and loot.',
 'change_key': 'CHANGE',
 'press_key': 'PRESS A KEY',
 'no_key': 'NONE',
 'right': 'RIGHT',
 'left': 'LEFT',
 'commands': 'COMMANDS',
 'keyboard': 'KEYBOARD / MOUSE',
 'controller': 'CONTROLLER',
 'command_third_person': 'THIRD PERSON',
 'command_third_person_desc': 'Turn third person on or off.',
 'command_shoulder': 'SWITCH SHOULDER',
 'command_shoulder_desc': 'Move the camera to the other shoulder.',
 'command_orbit': 'ORBIT CAMERA',
 'command_orbit_desc': 'Turn the Orbit Camera on or off.',
 'command_tools': 'COMMAND OPTIONS',
 'command_tools_desc': 'Controller icons and camera command defaults.',
 'commands_reset': 'DEFAULT KEYS',
 'controller_icons': 'CONTROLLER ICONS',
 'command_zoom_in': 'ORBIT CAMERA ZOOM IN',
 'command_zoom_in_desc': 'One step per press, in the Orbit Camera.',
 'command_zoom_out': 'ORBIT CAMERA ZOOM OUT',
 'command_zoom_out_desc': 'One step per press, in the Orbit Camera.',
 'camera_draft_discarded': 'Camera mod changed: unsaved camera settings were discarded.'}
FR = {'camera': 'CAMÉRA',
 'camera_desc': 'Vue, champ de vision et loot.',
 'change_key': 'MODIFIER',
 'press_key': 'APPUIE SUR UNE TOUCHE',
 'no_key': 'AUCUNE',
 'right': 'DROITE',
 'left': 'GAUCHE',
 'commands': 'COMMANDES',
 'keyboard': 'CLAVIER / SOURIS',
 'controller': 'MANETTE',
 'command_third_person': 'TROISIÈME PERSONNE',
 'command_third_person_desc': 'Active ou coupe la vue à la troisième personne.',
 'command_shoulder': "CHANGER D'ÉPAULE",
 'command_shoulder_desc': "Place la caméra sur l'autre épaule.",
 'command_orbit': 'CAMÉRA ORBITALE',
 'command_orbit_desc': 'Active ou coupe la caméra orbitale.',
 'command_tools': 'OPTIONS DES COMMANDES',
 'command_tools_desc': "Icônes de manette et touches caméra d'origine.",
 'commands_reset': "TOUCHES D'ORIGINE",
 'controller_icons': 'ICÔNES DE MANETTE',
 'command_zoom_in': 'RAPPROCHER LA CAMÉRA',
 'command_zoom_in_desc': 'Un cran par appui, en caméra orbitale.',
 'command_zoom_out': 'ÉLOIGNER LA CAMÉRA',
 'command_zoom_out_desc': 'Un cran par appui, en caméra orbitale.',
 'camera_draft_discarded': 'Mod caméra changé : les réglages caméra non enregistrés ont été '
                           'annulés.'}
FR_OPTIONS = {'third_person': ('Troisième personne', 'Garde la caméra derrière le personnage à pied.'),
 'shoulder_left': ('Épaule', 'Place la caméra à gauche ou à droite du personnage.'),
 'orbit': ('Caméra orbitale', 'La caméra tourne librement autour du personnage.'),
 'custom_fov': ('FOV personnalisé', 'Utilise le FOV ci-dessous à la place de celui du jeu.'),
 'fov': ('FOV', "Champ de vision, jusqu'à 150."),
 'extended_loot': ('Portée du loot augmentée',
                   'Ramasse le loot et ouvre les coffres de plus loin.'),
 'loot_reach': ('Portée du loot', '1 : portée du jeu ; 2 : deux fois plus loin.')}
