# Generated by sync_menu_ui; edit canonical sources.
"""Shared settings-form cancellation and generic transaction notices."""


class Lifecycle:
    def close_deadline(self):
        return self.model.transaction.deadline

    def close_ready(self):
        return self.model.cancel_transaction()

    def close_abort(self):
        self.model.transaction.abort()

    def failure_notice(self):
        return getattr(self.model.transaction, "failure_reason", "failed") or "failed"
