# Generated by sync_menu_ui; edit canonical sources.
"""SENSITIVITY's weapon-type rows (Kevin, 2026-10-07 and 2026-10-08): folded under their switch, and drawn as the
same bars as every other number of the window. Kevin first asked for arrows, then found a page mixing arrows and bars
for the same kind of setting inconsistent (2026-10-08, 3 h 50: « on aurait dû conserver un seul des deux »).

The rows fold away while the switch is off, and fade outside third person like the switch itself. The optic zooms
fold the same way under their own switch (Kevin, 2026-10-09: « une option dépliable » for the zooms), drawn after the
weapon rows and outside them: the two switches are independent (Kevin, 2026-10-10: « ce sont deux réglages
indépendants »).
"""

from . import panel_shortcut as sc, panel_theme as t, panel_widgets as w

# The runtime's look_sensitivity_options.WEAPON_PREFIX, per-weapon and per-optic switches
# (test_movement_weapon_sensitivity.py).
PREFIX = "sensitivity_weapon_"
SWITCH = "sensitivity_weapons"
OPTICS = PREFIX + "sniper_optics"
OPTIC_PREFIX = PREFIX + "sniper_x"


def split(options):
    """The switch's ordinary rows, then the weapon types drawn here."""
    options = tuple(options)
    return ([option for option in options if not option.identifier.startswith(PREFIX)],
            [option for option in options if option.identifier.startswith(PREFIX)])


def _visibility(shown):
    return w.enum("ESlateVisibility", "Visible" if shown else "Collapsed")


def _folded(rows, widgets, name):
    """A box of rows, so folding it takes their separators too."""
    box = w.new("VerticalBox", rows)
    box.SetVisibility(_visibility(False))  # until the form's first poll reads its switch
    w.column(rows, box)
    widgets[name] = box
    return box


def build(rows, options, widgets, template):
    weapons = [option for option in options if option.identifier != OPTICS
               and not option.identifier.startswith(OPTIC_PREFIX)]
    sc.rows(_folded(rows, widgets, "weapons:rows"), weapons, widgets, template)
    sc.rows(rows, [option for option in options if option.identifier == OPTICS], widgets, template)
    zooms = [option for option in options if option.identifier.startswith(OPTIC_PREFIX)]
    sc.rows(_folded(rows, widgets, "weapons:optics"), zooms, widgets, template)
    for option in options:
        # The window's labels write every setting's description; a weapon type's name says it all, the per-optic
        # switch's says what it unfolds.
        if option.identifier != OPTICS:
            widgets[f"description:{option.identifier}"].SetVisibility(_visibility(False))


def poll(form, widgets, _now):
    enabled = form.shown.get("third_person", True) is True and not form.model.camera_elsewhere
    for name, switch in (("weapons:rows", SWITCH), ("weapons:optics", OPTICS)):
        box = widgets[name]
        box.SetVisibility(_visibility(form.shown.get(switch) is True))
        box.SetIsEnabled(enabled)
        box.SetRenderOpacity(1.0 if enabled else t.OPACITY_DISABLED)
