# Generated by sync_menu_ui; edit canonical sources.
"""The camera settings over five sidebar pages (Kevin, 2026-10-06): what each page holds and shows."""

from mods_base import NestedOption

from .panel_camera_text import EN

# DYNAMIC CAMERA last: a page index saved before it still names the same page.
PAGES = ("camera", "aiming", "orbit_camera", "loot", "dynamic_camera")
# Spacing and height shape the view on foot as well as aiming, so they stay on CAMERA; the zoom is aiming only.
FRAMING = {"camera": ("horizontal", "height"), "aiming": ("zoom",)}
# Orbit also works from first person; only aiming needs the third-person switch.
NEEDS_THIRD_PERSON = ("aiming",)
# Engine units are centimetres; the Orbit distance reads in metres.
METRES = ("orbit_distance",)


def page_texts(texts):
    return {key: texts[f"{key}_page"] for key in PAGES}


def groups(settings, fov):
    """Presentation groups only: the SDK never registers them, so saved settings keep their flat identifiers."""
    contents = ([settings.third_person, settings.shoulder_left, *settings.shoulder_transition.options, *fov], [settings.third_person_ads],
                [settings.orbit, settings.zoom.option], list(settings.loot.options),
                [*settings.speed_fov.options, *settings.dynamic.options])
    descriptions = page_texts(EN)
    return tuple(NestedOption(f"{key}_menu", options, display_name=EN[key].title(), description=descriptions[key])
                 for key, options in zip(PAGES, contents))


def build(rows, key, group, widgets, template):
    from . import panel_ownership, panel_shortcut as sc
    if key in PAGES:
        # One section per page: another camera mod's ownership hides every camera setting.
        rows = panel_ownership.section(rows, widgets, f"{key}:settings")
    if key == "dynamic_camera":
        from . import panel_dynamic
        panel_dynamic.build(rows, group.children, widgets, template)
    else:
        sc.rows(rows, group.children, widgets, template)
    if key in FRAMING:
        from . import panel_framing
        panel_framing.build(rows, widgets, template, FRAMING[key])


def description(form, group, key, language):
    from . import panel_i18n as i18n
    text = i18n.group_text(group, key, language)
    if key in NEEDS_THIRD_PERSON and form.shown.get("third_person") is not True:
        text += "\n" + i18n.text("third_person_needed", language)
    return text


def refresh(widgets, key, language):
    if key == "dynamic_camera":
        from . import panel_dynamic
        panel_dynamic.refresh(widgets, language)


def metres(centimetres, language):
    text = f"{centimetres / 100:.2f}".rstrip("0").rstrip(".")
    return (text.replace(".", ",") if language == "FR" else text) + " m"


def show_unit(widgets, option, value, language):
    key = option.identifier
    if key in METRES:
        for name, number in (("value", value), ("low", option.min_value), ("high", option.max_value)):
            widgets[f"{name}:{key}"].SetText(metres(number, language))
