# Generated by sync_menu_ui; edit canonical sources.
"""Camera texts generated from Apex Movement's menu, whose Options page shows the same settings.
"""

EN = {'camera_refused': 'The camera could not confirm this change. It was not saved.',
 'camera_timeout': 'The camera did not respond. Previous settings were restored. Try again in a '
                   'moment.',
 'undone_partial': 'Settings restored, except the camera: another mod controls it.',
 'camera': 'CAMERA',
 'camera_desc': 'View, field of view and loot.',
 'change_key': 'CHANGE',
 'press_key': 'PRESS A KEY',
 'no_key': 'NONE',
 'right': 'RIGHT',
 'left': 'LEFT',
 'commands': 'COMMANDS',
 'keyboard': 'KEYBOARD / MOUSE',
 'controller': 'CONTROLLER',
 'command_third_person': 'THIRD PERSON',
 'command_third_person_desc': 'Turn third person on or off.',
 'command_shoulder': 'SWITCH SHOULDER',
 'command_shoulder_desc': 'Move the camera to the other shoulder.',
 'command_orbit': 'ORBIT CAMERA',
 'command_orbit_desc': 'Turn the Orbit Camera on or off.',
 'command_tools': 'COMMAND OPTIONS',
 'command_tools_desc': 'Controller icons and camera command defaults.',
 'commands_reset': 'DEFAULT KEYS',
 'controller_icons': 'CONTROLLER ICONS',
 'command_zoom_in': 'ORBIT CAMERA ZOOM IN',
 'command_zoom_in_desc': 'One step per press, in the Orbit Camera.',
 'command_zoom_out': 'ORBIT CAMERA ZOOM OUT',
 'command_zoom_out_desc': 'One step per press, in the Orbit Camera.',
 'command_free_look': 'FREE LOOK',
 'command_free_look_desc': 'Hold to turn the camera while you keep your direction.',
 'command_camera_distance': 'CAMERA DISTANCE',
 'command_camera_distance_desc': 'Close, normal or far, in third person.',
 'command_sniper_zoom': 'OPTIC ZOOM',
 'command_sniper_zoom_desc': 'While aiming with several zooms ticked, switch to the next one.',
 'popup_optics': 'OPTICS',
 'popup_optics_desc': "Each weapon type's zoom in third person.",
 'optics_help_text': 'BDL4: the weapon aims as in the game, in first person.\n'
                     '\n'
                     'x1: the weapon aims at the shoulder with a light zoom.\n'
                     '\n'
                     'x2 and up: the weapon aims at the shoulder with that zoom.\n'
                     '\n'
                     'Several zooms ticked: while aiming, the zoom key goes to the next one, '
                     'smallest to largest, then back to the first. The next aim with that weapon '
                     'type starts on the last zoom used.',
 'optics_help_key': 'ZOOM KEY',
 'optics_help_commands': 'Change it on the COMMANDS page.',
 'camera_draft_discarded': 'Camera mod changed: unsaved camera settings were discarded.',
 'camera_outdated': 'Camera mods of different versions are loaded. Update Apex Movement, Omni '
                    'Sprint and Third Person & FOV, then restart the game.',
 'camera_elsewhere': 'Another camera mod controls the camera. Use its menu to adjust it.',
 'framing_saved_unavailable': 'Saved. Framing preview is unavailable here.',
 'framing_saved_partial': 'Saved. Part of the framing preview is unavailable here; check the '
                          'camera rows.',
 'camera_page': 'View on foot, field of view and Free Look.',
 'aiming': 'AIMING',
 'aiming_page': 'Third-person aiming and zoom.',
 'orbit_camera': 'ORBIT CAMERA',
 'orbit_camera_page': 'Circles the character at the distance you choose.',
 'loot': 'LOOT',
 'loot_page': 'Pick up loot from farther away.',
 'third_person_needed': 'Turn on third person in the CAMERA tab.',
 'dynamic_camera': 'DYNAMIC CAMERA',
 'dynamic_camera_page': 'The camera follows the action: speed, jumps, crouching and driving.',
 'dynamic_fov': 'FIELD OF VIEW',
 'dynamic_fov_desc': 'Wider while sprinting or sliding.',
 'dynamic_framing': 'FRAMING',
 'dynamic_framing_desc': 'Back when running, jumping or driving fast, closer when crouched.',
 'dynamic_motion': 'MOTION',
 'dynamic_motion_desc': 'Soft inertia, and a faint drift when standing still.',
 'camera_view': 'CAMERA VIEW',
 'shoulder_view': 'SHOULDER VIEW',
 'shoulder': 'SHOULDER VIEW',
 'shoulder_desc': 'Pick the shoulder, and let the camera switch shoulders in front of a wall.',
 'sensitivity': 'SENSITIVITY',
 'sensitivity_page': "In percent of the game's own sensitivity: 100 changes nothing.",
 'omni_direction': 'OMNI DIRECTION',
 'omni_direction_page': 'The body follows your run, in third person.',
 'omni_full_turn': '360°',
 'omni_half_turn': '180°',
 'omni_dash': 'DASH',
 'omni_slide': 'SLIDE',
 'popup_omni_body': 'BODY ORIENTATION',
 'popup_omni_body_desc': 'The hunter turns toward the run.',
 'omni_body_help_text': 'In third person, the hunter turns toward the direction of the run instead '
                        'of keeping their back to the camera.\n'
                        '\n'
                        'The hunter turns back to the crosshair to shoot, throw a grenade, melee '
                        'or use the skill, and goes back to the run a second after the last '
                        'action.\n'
                        '\n'
                        'While aiming, the hunter faces the crosshair. During a slide, the body '
                        'keeps facing the slide.',
 'popup_omni_angle': 'ANGLE',
 'popup_omni_angle_desc': 'How far the body turns.',
 'omni_angle_help_text': '360°: the hunter turns toward the run on every side. Backward, the '
                         'hunter runs facing the camera.\n'
                         '\n'
                         '180°: the hunter turns on the sides and forward. Backward, the hunter '
                         'backs up with their back to the camera, as in the game.',
 'popup_omni_crouch': 'SIDES AND BACK',
 'popup_omni_crouch_desc': 'Crouching while sprinting sideways or backward.',
 'omni_crouch_help_text': 'When you sprint sideways or backward, crouching starts:\n'
                          '\n'
                          'DASH: the dash, as when you run without sprinting.\n'
                          '\n'
                          'SLIDE: a slide, as when sprinting forward.\n'
                          '\n'
                          'Forward, crouching always slides.'}
FR = {'camera_refused': 'La caméra n’a pas confirmé ce changement. Il n’a pas été enregistré.',
 'camera_timeout': 'La caméra n’a pas répondu. Les réglages précédents ont été rétablis. Réessaie '
                   'dans un moment.',
 'undone_partial': 'Réglages rétablis, sauf la caméra : un autre mod la contrôle.',
 'camera': 'CAMÉRA',
 'camera_desc': 'Vue, champ de vision et loot.',
 'change_key': 'MODIFIER',
 'press_key': 'APPUIE SUR UNE TOUCHE',
 'no_key': 'AUCUNE',
 'right': 'DROITE',
 'left': 'GAUCHE',
 'commands': 'COMMANDES',
 'keyboard': 'CLAVIER / SOURIS',
 'controller': 'MANETTE',
 'command_third_person': 'TROISIÈME PERSONNE',
 'command_third_person_desc': 'Active ou coupe la vue à la troisième personne.',
 'command_shoulder': "CHANGER D'ÉPAULE",
 'command_shoulder_desc': "Place la caméra sur l'autre épaule.",
 'command_orbit': 'CAMÉRA ORBITALE',
 'command_orbit_desc': 'Active ou coupe la caméra orbitale.',
 'command_tools': 'OPTIONS DES COMMANDES',
 'command_tools_desc': "Icônes de manette et touches caméra d'origine.",
 'commands_reset': "TOUCHES D'ORIGINE",
 'controller_icons': 'ICÔNES DE MANETTE',
 'command_zoom_in': 'RAPPROCHER LA CAMÉRA',
 'command_zoom_in_desc': 'Un cran par appui, en caméra orbitale.',
 'command_zoom_out': 'ÉLOIGNER LA CAMÉRA',
 'command_zoom_out_desc': 'Un cran par appui, en caméra orbitale.',
 'command_free_look': 'VUE LIBRE',
 'command_free_look_desc': 'Maintiens pour tourner la caméra en gardant ta direction.',
 'command_camera_distance': 'DISTANCE DE LA CAMÉRA',
 'command_camera_distance_desc': 'Proche, normale ou loin, à la troisième personne.',
 'command_sniper_zoom': "ZOOM DE L'OPTIQUE",
 'command_sniper_zoom_desc': 'En visée avec plusieurs zooms cochés, passe au suivant.',
 'popup_optics': 'OPTIQUES',
 'popup_optics_desc': "Le zoom de chaque type d'arme en troisième personne.",
 'optics_help_text': "BDL4 : l'arme vise comme dans le jeu, en première personne.\n"
                     '\n'
                     "x1 : l'arme vise à l'épaule avec un léger zoom.\n"
                     '\n'
                     "x2 et plus : l'arme vise à l'épaule avec ce zoom.\n"
                     '\n'
                     'Plusieurs zooms cochés : en visée, la touche de zoom passe au suivant, du '
                     'plus petit au plus grand, puis revient au premier. La visée suivante avec ce '
                     "type d'arme reprend le dernier zoom utilisé.",
 'optics_help_key': 'TOUCHE DE ZOOM',
 'optics_help_commands': "Elle se change dans l'onglet COMMANDES.",
 'camera_draft_discarded': 'Mod caméra changé : les réglages caméra non enregistrés ont été '
                           'annulés.',
 'camera_outdated': 'Des mods de caméra de versions différentes sont chargés. Mets à jour Apex '
                    'Movement, Omni Sprint et Third Person & FOV, puis relance le jeu.',
 'camera_elsewhere': 'Un autre mod contrôle la caméra. Règle-la dans son menu.',
 'framing_saved_unavailable': 'Enregistré. Aperçu du cadrage indisponible ici.',
 'framing_saved_partial': 'Enregistré. Aperçu du cadrage partiel ici ; consulte les lignes de la '
                          'caméra.',
 'camera_page': 'Vue à pied, champ de vision et vue libre.',
 'aiming': 'VISÉE',
 'aiming_page': 'Visée en troisième personne et zoom.',
 'orbit_camera': 'CAMÉRA ORBITALE',
 'orbit_camera_page': 'Tourne autour du personnage, à la distance de ton choix.',
 'loot': 'LOOT',
 'loot_page': 'Ramasse le loot de plus loin.',
 'third_person_needed': "Active la troisième personne dans l'onglet CAMÉRA.",
 'dynamic_camera': 'CAMÉRA DYNAMIQUE',
 'dynamic_camera_page': "La caméra suit l'action : vitesse, sauts, accroupi et conduite.",
 'dynamic_fov': 'CHAMP DE VISION',
 'dynamic_fov_desc': 'Plus large en sprint et en glissade.',
 'dynamic_framing': 'CADRAGE',
 'dynamic_framing_desc': 'Recule en courant, en sautant ou en roulant vite, se rapproche accroupi.',
 'dynamic_motion': 'MOUVEMENTS',
 'dynamic_motion_desc': "Une légère inertie, et un faible flottement à l'arrêt.",
 'camera_view': 'VUE CAMÉRA',
 'shoulder_view': 'VUE ÉPAULES',
 'shoulder': 'VUE ÉPAULES',
 'shoulder_desc': "Choisis l'épaule, et laisse la caméra changer d'épaule devant un mur.",
 'sensitivity': 'SENSIBILITÉ',
 'sensitivity_page': 'En pourcentage de la sensibilité du jeu : 100 ne change rien.',
 'omni_direction': 'OMNI DIRECTION',
 'omni_direction_page': 'Le corps suit ta course, en troisième personne.',
 'omni_full_turn': '360°',
 'omni_half_turn': '180°',
 'omni_dash': 'DASH',
 'omni_slide': 'GLISSADE',
 'popup_omni_body': 'ORIENTATION DU CORPS',
 'popup_omni_body_desc': 'Le chasseur se tourne vers sa course.',
 'omni_body_help_text': 'En troisième personne, le chasseur se tourne vers la direction où il '
                        'court, au lieu de rester dos à la caméra.\n'
                        '\n'
                        'Il se retourne vers le viseur quand tu tires, lances une grenade, frappes '
                        'au corps à corps ou utilises ta compétence, et reprend sa course une '
                        'seconde après ta dernière action.\n'
                        '\n'
                        'Quand tu vises, il fait face au viseur. Pendant une glissade, il reste '
                        'tourné vers la glissade.',
 'popup_omni_angle': 'ANGLE',
 'popup_omni_angle_desc': "Jusqu'où le corps se tourne.",
 'omni_angle_help_text': '360° : le chasseur se tourne vers sa course de tous les côtés. En '
                         'arrière, il court face à la caméra.\n'
                         '\n'
                         "180° : il se tourne sur les côtés et vers l'avant. En arrière, il recule "
                         'dos à la caméra, comme dans le jeu.',
 'popup_omni_crouch': 'CÔTÉS ET ARRIÈRE',
 'popup_omni_crouch_desc': "S'accroupir en sprint sur le côté ou en arrière.",
 'omni_crouch_help_text': "Quand tu sprintes sur le côté ou en arrière, s'accroupir lance :\n"
                          '\n'
                          'DASH : le dash, comme quand tu cours sans sprinter.\n'
                          '\n'
                          "GLISSADE : une glissade, comme en sprint vers l'avant.\n"
                          '\n'
                          "Vers l'avant, s'accroupir lance toujours une glissade.",
 'aim_third': 'Troisième personne',
 'aim_first': 'Première personne',
 'ads_unsupported': "Visée à l'épaule indisponible avec cette version. Garde la visée première "
                    "personne jusqu'à une mise à jour du mod.",
 'ads_unknown_weapon': 'Arme non reconnue : visée première personne conservée. Essaie une autre '
                       'arme.',
 'ads_heavy_native': 'Armes lourdes : visée première personne conservée.',
 'ads_wrong_thread': 'Présentation de visée indisponible : visée première personne conservée. '
                     'Signale ce problème avec le journal.',
 'ads_mode_unavailable': 'Vue de visée non confirmée : visée première personne conservée. Relâche '
                         'puis reprends la visée.',
 'ads_cleanup_pending': 'Retour à la vue du jeu en cours. Attends avant de changer de mod caméra.',
 'ads_install_failed': "Activation de la visée à l'épaule impossible. Relance le jeu ; si cela "
                       'persiste, signale-le avec le journal.'}
FR_OPTIONS = {'third_person': ('Troisième personne', 'Garde la caméra derrière le personnage à pied.'),
 'third_person_ads': ('Visée', "L'optique de chaque type d'arme se choisit ci-dessous."),
 'pistol_optics': ('Optique des pistolets',
                   "BDL4 rétablit la visée du jeu en première personne ; un zoom vise à l'épaule."),
 'smg_optics': ('Optique des mitraillettes',
                "BDL4 rétablit la visée du jeu en première personne ; un zoom vise à l'épaule."),
 'shotgun_optics': ('Optique des fusils à pompe',
                    'BDL4 rétablit la visée du jeu en première personne ; un zoom vise à '
                    "l'épaule."),
 'assault_optics': ("Optique des fusils d'assaut",
                    'BDL4 rétablit la visée du jeu en première personne ; un zoom vise à '
                    "l'épaule."),
 'sniper_optics': ('Optique des fusils de précision',
                   "BDL4 rétablit la visée du jeu en première personne ; un zoom vise à l'épaule."),
 'heavy_optics': ('Optique des armes lourdes',
                  "BDL4 rétablit la visée du jeu en première personne ; un zoom vise à l'épaule."),
 'shoulder_left': ("Changement d'épaule", 'Place la caméra à gauche ou à droite du personnage.'),
 'shoulder_auto': ("Changement d'épaule automatique",
                   "La caméra passe sur l'autre épaule quand un mur bouche la vue, puis revient."),
 'shoulder_auto_swap': ('Épaule automatique : délai de bascule',
                        'Temps pendant lequel un mur bouche la vue avant que la caméra change '
                        "d'épaule, en secondes."),
 'shoulder_auto_return': ('Épaule automatique : délai de retour',
                          'Temps de vue dégagée avant que la caméra revienne sur ton épaule, en '
                          'secondes.'),
 'camera_distance_close': ('Distance de la caméra : proche',
                           'Distance derrière toi en position proche, en mètres. La normale est à '
                           '2,56.'),
 'camera_distance_far': ('Distance de la caméra : loin',
                         'Distance derrière toi en position loin, en mètres. La normale est à '
                         '2,56.'),
 'sensitivity_look': ('Regard en troisième personne',
                      'Vitesse de la caméra en troisième personne, souris et manette, en '
                      'pourcentage de celle du jeu.'),
 'sensitivity_aim': ('Visée en troisième personne',
                     "Vitesse de la caméra en visant par-dessus l'épaule, souris et manette, en "
                     'pourcentage de celle du jeu.'),
 'sensitivity_weapons': ("Sensibilité par type d'arme",
                         "En visée en troisième personne, chaque type d'arme prend sa propre "
                         'valeur ci-dessous.'),
 'sensitivity_weapon_pistol': ('Pistolets',
                               'Vitesse de visée au pistolet, en pourcentage de celle du jeu.'),
 'sensitivity_weapon_smg': ('Mitraillettes',
                            'Vitesse de visée à la mitraillette, en pourcentage de celle du jeu.'),
 'sensitivity_weapon_shotgun': ('Fusils à pompe',
                                'Vitesse de visée au fusil à pompe, en pourcentage de celle du '
                                'jeu.'),
 'sensitivity_weapon_assault': ("Fusils d'assaut",
                                "Vitesse de visée au fusil d'assaut, en pourcentage de celle du "
                                'jeu.'),
 'sensitivity_weapon_sniper': ('Fusils de précision',
                               'Vitesse de visée au fusil de précision, en pourcentage de celle du '
                               'jeu.'),
 'sensitivity_weapon_heavy': ('Armes lourdes',
                              "Vitesse de visée à l'arme lourde, en pourcentage de celle du jeu."),
 'sensitivity_weapon_sniper_optics': ("Par zoom d'optique",
                                      'Chaque zoom prend sa propre valeur ci-dessous, avec toutes '
                                      'les armes.'),
 'sensitivity_weapon_sniper_x2': ('Optique x2',
                                  'Vitesse de visée avec le zoom x2, en pourcentage de celle du '
                                  'jeu.'),
 'sensitivity_weapon_sniper_x3': ('Optique x3',
                                  'Vitesse de visée avec le zoom x3, en pourcentage de celle du '
                                  'jeu.'),
 'sensitivity_weapon_sniper_x4': ('Optique x4',
                                  'Vitesse de visée avec le zoom x4, en pourcentage de celle du '
                                  'jeu.'),
 'sensitivity_weapon_sniper_x6': ('Optique x6',
                                  'Vitesse de visée avec le zoom x6, en pourcentage de celle du '
                                  'jeu.'),
 'sensitivity_weapon_sniper_x8': ('Optique x8',
                                  'Vitesse de visée avec le zoom x8, en pourcentage de celle du '
                                  'jeu.'),
 'shoulder_smooth': ("Changement d'épaule fluide",
                     'Déplace progressivement la caméra entre les deux épaules.'),
 'orbit_smooth': ('Transitions caméra fluides',
                  'Anime le décalage ajouté entre première et troisième personne et pour Orbit.'),
 'shoulder_seconds': ('Animation de transition',
                      "Durée commune du décalage d'épaule et des transitions caméra, en secondes."),
 'orbit': ('Caméra orbitale', 'La caméra tourne librement autour du personnage.'),
 'orbit_distance': ('Distance', 'Distance de la caméra, aussi réglée par les touches de zoom.'),
 'custom_fov': ('FOV personnalisé', 'Utilise le FOV ci-dessous à la place de celui du jeu.'),
 'fov': ('FOV', "Champ de vision, jusqu'à 150."),
 'extended_loot': ('Portée du loot augmentée',
                   'Ramasse le loot et ouvre les coffres de plus loin.'),
 'loot_reach': ('Portée du loot', '1 : portée du jeu ; 2 : deux fois plus loin.'),
 'speed_fov': ('FOV en vitesse', 'Élargit la vue quand tu sprintes.'),
 'speed_fov_gain': ('Élargissement', 'Champ de vision ajouté en sprint.'),
 'speed_fov_seconds': ('Transition', "Secondes pour s'élargir et pour revenir."),
 'action_framing': ("Cadrage selon l'action",
                    "Recule la caméra en courant, en l'air ou en roulant vite, et la rapproche "
                    'accroupi.'),
 'action_framing_strength': ('Force du cadrage',
                             '100 % par défaut ; plus bas, plus doux ; plus haut, plus fort.'),
 'camera_motion': ('Mouvements de caméra',
                   'La caméra suit en douceur tes changements de vitesse, et bouge un peu à '
                   "l'arrêt."),
 'camera_motion_strength': ('Force des mouvements',
                            '100 % par défaut ; plus bas, plus doux ; plus haut, plus fort.'),
 'free_look': ('Vue libre', 'Maintiens sa touche pour tourner la caméra en gardant ta direction.'),
 'free_look_keyboard_hold': ('Vue libre : maintenir au clavier',
                             'OUI : la vue libre dure tant que la touche est tenue. NON : un appui '
                             "l'allume, un autre l'éteint."),
 'free_look_controller_hold': ('Vue libre : maintenir à la manette',
                               'OUI : la vue libre dure tant que le bouton est tenu. NON : un '
                               "appui l'allume, un autre l'éteint."),
 'free_look_hold_time': ('Vue libre : durée du maintien',
                         'Temps à tenir avant que la vue libre démarre, en secondes.'),
 'omni_body': ('Orientation du corps', 'Le chasseur se tourne vers la direction où il court.'),
 'omni_angle': ('Angle',
                '360° : de tous les côtés. 180° : en arrière, il recule comme dans le jeu.'),
 'omni_direction_sprint': ('Sprint dans toutes les directions',
                           'Sprinte aussi sur les côtés et en arrière.'),
 'omni_crouch': ('Côtés et arrière',
                 "En sprint sur le côté ou en arrière, s'accroupir lance un dash ou une glissade.")}
