# Generated by sync_menu_ui; edit canonical sources.
"""A setting chosen among a few names: one button per name side by side, the heirloom's mode, APEX or BORDERLANDS, and
its model (Kevin, 2026-09-26, sketch A; 2026-09-29, sketch H2, cosmetics/heirloom/docs/esquisses_menu/); or, for a
row of menu.ARROWS, two arrows around the chosen name and its place among the names in the value box, the heirloom's
skin (sketch H2: a heirloom may keep many, the row stays one line). Apex Grapple's rows hold only switches and
sliders; its pages, form, labels and model call this for a spinner (outils/sync_menu_heirloom_pages.py).

The buttons are the switches' own, gold for the choice in use, as the sketches drew them; the arrows are the header's
EN and FR buttons. Past the last name, the next arrow comes back to the first.
"""

from . import menu, panel_buttons as b, panel_en, panel_fr, panel_slider as s, panel_text as tx, panel_theme as t
from . import panel_widgets as w

# The name's box, as wide as sketch H2 drew it and a little more, for the longest names in French.
NAME_WIDTH = 260
ARROWS = (("previous", "<", -1), ("next", ">", 1))


def is_choice(option):
    # mods_base's SpinnerOption: its value is one of its choices.
    return hasattr(option, "choices")


def _name(option, choice):
    return f"setting:{option.identifier}:{choice}"


def label(choice, language):
    """A name as the window writes it: its words in the language shown, else in English, else the name itself."""
    words = panel_fr.CHOICES.get(choice) if language == "FR" else None
    return (words or panel_en.CHOICES.get(choice) or choice).upper()


def controls(owner, widgets, option, template):
    """The row's control, and its value box for a row of arrows; the control registered as setting:<identifier>:
    stilled, it stills its buttons."""
    if option.identifier not in menu.ARROWS:
        return (buttons(owner, widgets, option, template),)
    key = option.identifier
    line = w.new("HorizontalBox", owner)
    box = w.border(line, t.COLOR_INK, w.pad(tx.inset(t.SPACE_1, "value"), t.SPACE_3))
    widgets[f"choice:{key}"] = tx.text(box, "", "value", center=True)
    box.SetContent(widgets[f"choice:{key}"])
    w.row(line, b.button(line, widgets, f"setting:{key}:previous", "lang", template, "lang_off"), valign="Center")
    w.row(line, w.sized(line, w.slant(box), width=NAME_WIDTH), padding=w.pad(0, t.SPACE_3), valign="Center")
    w.row(line, b.button(line, widgets, f"setting:{key}:next", "lang", template, "lang_off"), valign="Center")
    widgets[f"setting:{key}"] = line
    return line, s.value_box(owner, widgets, key)


def buttons(owner, widgets, option, template):
    """The choices' buttons in one line, the line registered as setting:<identifier>: stilled, it stills them all."""
    line = w.new("HorizontalBox", owner)
    for index, choice in enumerate(option.choices):
        w.row(line, b.button(line, widgets, _name(option, choice), "switch", template, "off"),
              padding=w.pad(0, 0, 0, t.SPACE_3 if index else 0), valign="Center")
    widgets[f"setting:{option.identifier}"] = line
    return line


def _clickable(option):
    if option.identifier in menu.ARROWS:
        return [f"setting:{option.identifier}:{name}" for name, _, _ in ARROWS]
    return [_name(option, choice) for choice in option.choices]


def release(widgets, option):
    """Forgets a click not read yet: the buttons latch, as the switches do."""
    for name in _clickable(option):
        widgets[name].SetIsChecked(False)


def _shown(option, current):
    """The name the window shows for `current`: the first, the heirloom's own look, for one it does not offer."""
    return current if current in option.choices else option.choices[0]


def taken(take, widgets, option, current):
    """The choice clicked since the last look, read with the form's `take`, from `current` for the arrows; None
    without a click."""
    if option.identifier in menu.ARROWS:
        choices = list(option.choices)
        step = sum(move for name, _, move in ARROWS if take(widgets[f"setting:{option.identifier}:{name}"]))
        return choices[(choices.index(_shown(option, current)) + step) % len(choices)] if step else None
    clicked = None
    for choice in option.choices:
        if take(widgets[_name(option, choice)]) and clicked is None:
            clicked = choice
    return clicked


def paint(widgets, option, current, language):
    key = option.identifier
    if key in menu.ARROWS:
        choices = list(option.choices)
        for name, mark, _ in ARROWS:
            widgets[f"setting:{key}:{name}_label"].SetText(mark)
        widgets[f"choice:{key}"].SetText(label(_shown(option, current), language))
        widgets[f"value:{key}"].SetText(f"{choices.index(_shown(option, current)) + 1}/{len(choices)}")
        return
    for choice in option.choices:
        widgets[f"{_name(option, choice)}_label"].SetText(label(choice, language))
        b.paint(widgets, _name(option, choice), "on" if choice == current else "off")
