# Generated by sync_menu_ui; edit canonical sources.
"""Shared settings-form widget lifetime, closing and transaction notices."""


class Lifecycle:
    def resolve(self):
        widgets = {name: reference() for name, reference in self.widgets.items()}
        if any(widget is None for widget in widgets.values()):
            raise ValueError("Window widget unavailable")
        return widgets

    def close_deadline(self):
        return self.model.transaction.deadline

    def close_ready(self):
        return self.model.cancel_transaction()

    def close_abort(self):
        self.model.transaction.abort()

    def escape(self):
        """Escape closes the window as the Close button does, saving what is still pending (control_escape)."""
        return self.flush(self.resolve())

    def failure_notice(self):
        return getattr(self.model.transaction, "failure_reason", "failed") or "failed"
