# Generated by sync_menu_ui; edit canonical sources.
"""Restore and Undo compose synchronous settings under one shared deadline."""


class Restore:
    success_notice = "saved"

    def restore(self):
        previous = tuple((option, option.value) for option in self.options.values())
        if not previous:
            return False
        return self._start_global(tuple((option, option.default_value) for option, _ in previous),
                                  "restore", previous)

    def undo(self):
        if not self._undo:
            return False
        changes = self._undo
        previous = tuple((option, option.value) for option, _ in changes)
        return self._start_global(changes, "undo", previous)

    def _start_global(self, changes, kind, previous):
        self.success_notice = {"restore": "restored", "undo": "undone"}[kind]
        self._restore_plan = (kind, self._undo)
        outcome = self.transaction.start(changes, previous, kind)
        if outcome is None:
            return None
        return self._finish_global(outcome, label=False)

    def _finish_global(self, outcome, label):
        kind, former_undo = self._restore_plan
        success = self._complete(outcome)
        if not success:
            self._undo = () if kind == "restore" else former_undo
        self._restore_plan = None
        if not label:
            return success
        return self.success_notice if success else "failed"
