"""French labels and explanations for all gameplay and interface controls."""

TEXT = {
    "shot": "LE TIR", "pull": "LA TRACTION", "release": "DÉCROCHAGE", "controls": "COMMANDES",
    "close": "FERMER", "restore": "RÉGLAGES D’ORIGINE", "undo": "ANNULER LE RESET",
    "enabled": "ACTIVÉ", "disabled": "DÉSACTIVÉ", "on": "OUI", "off": "NON",
    "by": "PAR", "version": "VERSION", "settings": "RÉGLAGES",
    "ready": "Sauvegarde automatique. Fermer revient à la liste des mods.",
    "saved": "Enregistré.", "failed": "Échec de sauvegarde. Réglages précédents conservés. Réessaie.",
    "restored": "Réglages d’origine restaurés. Tu peux annuler cette restauration.",
    "undone": "Réglages précédents rétablis.",
    "controls_intro": "Choisis un emplacement, puis appuie sur une touche clavier, souris ou manette. Les choix complets sont enregistrés automatiquement.",
    "two": "Deux touches à maintenir ensemble", "first": "1. CHOISIR UNE TOUCHE",
    "second": "2. CHOISIR LA DEUXIÈME TOUCHE", "listening": "APPUIE SUR TA TOUCHE",
    "reset_controls": "TOUCHES D’ORIGINE", "one_hint": "Choisis une touche. Elle sera enregistrée immédiatement.",
    "two_hint": "Choisis deux touches du même périphérique. Maintiens-les ensemble pour lancer le grappin.",
    "escape_hint": "Échap annule la saisie. La touche console est réservée. Chaque touche garde son action normale lorsqu’elle est pressée seule.",
    "keyboard": "Clavier / souris", "gamepad": "Manette", "game_controls": "Commandes du jeu",
    "invalid_keys": "Non enregistré. Choisis des touches différentes du même périphérique. Échap et la touche console sont réservées.",
    "controls_saved": "Commandes enregistrées.", "controls_reset": "Commandes du grappin restaurées.",
    "current_controls": "Touches actuelles",
    "controller_icons": "ICÔNES MANETTE", "PS5": "PLAYSTATION", "XSX": "XBOX",
    "game_controls_pending": "Commandes du jeu (disponibles en partie)",
    "reserved_key": "Non enregistré : cette touche est réservée à la console ou à l’annulation. Commandes précédentes conservées.",
}
OPTIONS = {
    "grapple_range": ("Portée", "Distance max. du crochet. 3000 = 30 mètres."),
    "hook_speed": ("Vitesse du crochet", "Vitesse du crochet jusqu'à sa cible."),
    "melee_wins": ("Priorité au corps à corps", "Sur un ennemi, la touche frappe au lieu de lancer le grappin."),
    "stamina_cost": ("Coût en endurance", "Part de la barre d'endurance dépensée par tir. 33 = trois tirs, 0 = gratuit."),
    "punch_range": ("Portée du corps à corps", "Un ennemi plus proche que cette distance reçoit un coup de poing."),
    "keep_game_grapple": ("Garder le grappin du jeu", "Les points d’accroche du jeu gardent le grappin du jeu."),
    "show_rope": ("Afficher la corde", "Affiche la corde et l’animation du bras."),
    "pull_strength": ("Force de traction", "Force avec laquelle la corde te tire."),
    "pull_speed_cap": ("Vitesse max. de traction", "Vitesse max. donnée par la corde. Ton élan s’y ajoute."),
    "rope_carry": ("Portage par la corde", "Part du poids portée par la corde : à 100 %, elle te porte ; à 0 %, la gravité agit pendant toute la traction."),
    "steer_strength": ("Force de direction", "À quel point le stick courbe ta trajectoire."),
    "steer_speed_cap": ("Vitesse max. de direction", "Vitesse latérale maximale ajoutée par le stick pendant la traction."),
    "release_on_key_up": ("Maintenir pour continuer à tirer", "Relâcher la touche lâche le grappin. Un appui bref tire jusqu’au bout."),
    "arrival_distance": ("Distance d’arrivée", "La traction s’arrête à cette distance de l’accroche."),
    "longest_pull": ("Durée max. de traction", "En secondes. 0 = sans limite."),
    "takeoff_lift": ("Élan au décollage", "Petit saut au départ depuis le sol. À 0, tu pars au ras du sol."),
    "ground_grace": ("Temps de décollage", "Le sol est ignoré ce temps-là au départ, pour décoller."),
    "release_on_landing": ("Lâcher à l’atterrissage", "Toucher le sol met fin à la traction."),
    "block_jump": ("Garder le saut en se détachant", "Sauter pour lâcher le grappin ne consomme pas de saut."),
}
GROUPS = {
    "shot": "Portée, vitesse du crochet, corps à corps et effets visuels.",
    "pull": "Force de la corde, vitesse et contrôle de la trajectoire.",
    "release": "Ce qui termine la traction. La vitesse atteinte est conservée.",
}
