"""French labels and explanations for all gameplay and interface controls."""

TEXT = {
    "shot": "LE TIR", "pull": "LA TRACTION", "release": "DÉCROCHAGE", "controls": "COMMANDES",
    "close": "FERMER", "restore": "RÉGLAGES D’ORIGINE", "undo": "ANNULER LE RESET",
    "enabled": "ACTIVÉ", "disabled": "DÉSACTIVÉ", "on": "OUI", "off": "NON",
    "by": "PAR", "version": "VERSION", "settings": "RÉGLAGES",
    "ready": "Sauvegarde automatique. Fermer revient à la liste des mods.",
    "saved": "Enregistré.", "failed": "Échec de sauvegarde. Réglages précédents conservés. Réessaie.",
    "restored": "Réglages d’origine restaurés. Tu peux annuler cette restauration.",
    "undone": "Réglages précédents rétablis.",
    "controls_intro": "Choisis un emplacement, puis appuie sur une touche clavier, souris ou manette. Les choix complets sont enregistrés automatiquement.",
    "two": "Deux touches à maintenir ensemble", "first": "1. CHOISIR UNE TOUCHE",
    "second": "2. CHOISIR LA DEUXIÈME TOUCHE", "listening": "APPUIE SUR TA TOUCHE",
    "reset_controls": "TOUCHES D’ORIGINE", "one_hint": "Choisis une touche. Elle sera enregistrée immédiatement.",
    "two_hint": "Choisis deux touches du même périphérique. Maintiens-les ensemble pour lancer le grappin.",
    "escape_hint": "Échap annule la saisie. La touche console est réservée. Chaque touche garde son action normale lorsqu’elle est pressée seule.",
    "keyboard": "Clavier / souris", "gamepad": "Manette", "game_controls": "Commandes du jeu",
    "invalid_keys": "Non enregistré. Choisis des touches différentes du même périphérique. Échap et la touche console sont réservées.",
    "controls_saved": "Commandes enregistrées.", "controls_reset": "Commandes du grappin restaurées.",
    "current_controls": "Touches actuelles",
    "controller_icons": "ICÔNES MANETTE", "PS5": "PLAYSTATION", "XSX": "XBOX",
    "game_controls_pending": "Commandes du jeu (disponibles en partie)",
    "reserved_key": "Non enregistré : cette touche est réservée à la console ou à l’annulation. Commandes précédentes conservées.",
}
OPTIONS = {
    "grapple_range": ("Portée", "Distance maximale du crochet, en centimètres. 3000 correspond à 30 mètres."),
    "hook_speed": ("Vitesse du crochet", "Vitesse du crochet vers la surface. Tu peux encore te déplacer et sauter pendant son vol."),
    "melee_wins": ("Priorité au corps à corps", "Viser un ennemi donne un coup ; viser une surface lance le grappin. Désactivé, le grappin est prioritaire."),
    "stamina_cost": ("Coût en endurance", "Part de la barre d'endurance qu'un tir dépense, celle que le dash et le vol plané utilisent déjà, en pourcentage. 33 donne trois tirs sur une barre pleine. À 0, un tir ne coûte rien et n'attend jamais."),
    "punch_range": ("Portée du corps à corps", "Les ennemis proches et les impacts non identifiés gardent le coup de poing. Les surfaces connues restent accrochables de près."),
    "keep_game_grapple": ("Garder le grappin du jeu", "Les points d’accroche natifs utilisent le grappin du jeu. Désactivé, le mod gère tous les tirs."),
    "show_rope": ("Afficher la corde", "Affiche la corde du jeu et son animation de bras. Désactiver cet effet ne retire pas la traction."),
    "pull_strength": ("Force de traction", "Force de la corde par rapport à la gravité. Une force plus élevée permet de décoller avec un tir moins incliné."),
    "pull_speed_cap": ("Vitesse max. de traction", "Vitesse que la corde peut ajouter vers l’accroche. L’élan déjà présent est conservé en plus."),
    "rope_carry": ("Portage par la corde", "Part du poids portée par la corde : à 100 %, elle te porte ; à 0 %, la gravité agit pendant toute la traction."),
    "steer_strength": ("Force de direction", "Force du stick pendant la traction. Oriente le stick et la caméra pour courber la trajectoire."),
    "steer_speed_cap": ("Vitesse max. de direction", "Vitesse latérale maximale ajoutée par le stick pendant la traction."),
    "release_on_key_up": ("Maintenir pour continuer à tirer", "Un clic bref donne une traction complète. Relâcher une touche maintenue après l’accroche permet de lâcher."),
    "arrival_distance": ("Distance d’arrivée", "Distance à laquelle la traction s’arrête. Pour un tir court, elle est limitée à la moitié de la distance initiale."),
    "longest_pull": ("Durée max. de traction", "Durée maximale en secondes. 0 signifie sans limite. Une durée courte coupe les grands balancements."),
    "takeoff_lift": ("Élan au décollage", "Impulsion verticale au départ depuis le sol. À 0, le grappin commence par tirer au ras du sol."),
    "ground_grace": ("Temps de décollage", "Délai pendant lequel le sol est ignoré au départ, pour laisser le temps de décoller."),
    "release_on_landing": ("Lâcher à l’atterrissage", "Toucher le sol met fin à la traction."),
    "block_jump": ("Garder le saut en se détachant", "Sauter lâche le grappin accroché. Activé, cet appui ne dépense aucun saut ; le suivant saute normalement."),
}
GROUPS = {
    "shot": "Portée, vitesse du crochet, corps à corps et effets visuels.",
    "pull": "Force de la corde, vitesse et contrôle de la trajectoire.",
    "release": "Ce qui termine la traction. La vitesse atteinte est conservée.",
}
