"""Benefix Ohm Attack: hold a key to raise the left hand and fire one of the game's own beams from it.

Named by Kevin on 2026-10-01 after the game's weapon the idea comes from, the Benefix Ohm I Got. The beam costs its
own energy, hits what it is on for a damage that grows with the player's level, and is made of the element chosen
in the mod's window (menu.py; the window is our other mods', generated by
docs/attaque-rayon/outils/menu_window.py). Its decisions, trials and tools are in docs/attaque-rayon/.
"""

from mods_base import build_mod

from . import attack, bar, bounce, catch, control_config, damage, enemy, foes, frame, hand, keys, lock, panel_open
from . import panel_preferences, report, settings

__version__ = "1.0.4"
__author__ = "kevin-hDev"


def _on_enable() -> None:
    report.reset()
    # What the game refused once is asked of it again: the walk of its characters, who is a friend, the catch, the
    # lock, the bounce.
    foes.restart()
    enemy.forget()
    catch.restart()
    lock.restart()
    bounce.restart()
    damage.forget()
    hand.forget()
    keys.align()
    report.note(f"enabled, version {__version__}")
    bar.start()


def _on_disable() -> None:
    attack.stop()
    bar.stop()
    report.note("disabled")


mod = build_mod(
    name="Benefix Ohm Attack",
    hooks=[frame.tick],
    keybinds=[keys.keyboard_bind, keys.controller_bind],
    # The window's language, icons, page and theme are hidden options: the SDK's menu lists the settings and the keys.
    options=[*settings.ALL, *control_config.ALL, *panel_preferences.ALL],
    on_enable=_on_enable,
    on_disable=_on_disable,
)
panel_open.install(mod)

# mods_base only enables a mod whose settings file says so; a fresh install has none and would stay off.
if mod.settings_file is not None and not mod.settings_file.exists():
    mod.enable()
