# Generated: the settings window Kevin's mods share, taken from Apex Heirloom's and put under this mod's names.
# Its comments may speak of that mod. Never edited by hand: the window's generator writes this file.
# Generated by sync_menu_ui; edit canonical sources.
"""The settings window owns the screen while it is open: a layer over the game keeps every click in the window.

Kevin, 2026-10-06: a click beside the window handed the mouse to the game, as a desktop window loses its focus.
Slate gives a click's keyboard focus to the nearest focusable widget under the pointer, and outside the buttons that
was the game's own viewport. Now a layer covers the screen, blurring the game behind, and the window's holder can
take the focus, so no click reaches the game. The window keeps its size's share of the screen, centred.
"""

import unrealsdk

from . import panel_theme as t, panel_widgets as w, panel_window_size as size


def held(pc, window):
    """Wraps the window in a UserWidget, which Slate keeps alive for as long as it is on screen.

    Nothing held the bare ScaleBox: the garbage collector removed the window 35 and 50 s after it opened, twice
    without a click on Close (journal of 2026-09-21, "window_gone"). Matt's BL4 Mods Menu builds its window the same
    way (single source).
    """
    holder = w.new("UserWidget", pc)
    holder.bIsFocusable = True
    tree = w.new("WidgetTree", holder)
    holder.WidgetTree = tree
    screen = w.new("CanvasPanel", holder)
    tree.RootWidget = screen
    layer = _layer(screen)
    layer.SetVisibility(w.enum("ESlateVisibility", "Visible"))  # hit, though it draws nothing: it takes the clicks
    layer.SetCursor(w.enum("EMouseCursor", "Default"))
    _span(screen.AddChildToCanvas(layer), 0.0, 0.0)
    width, height = size.share()
    _span(screen.AddChildToCanvas(window), (1 - width) / 2, (1 - height) / 2)
    return holder


def _layer(owner):
    """Blurs the game behind the window, as behind an app's pop-up (Kevin, 2026-10-06). Not yet seen in BL4: if the
    blur cannot be made, a clear layer takes its place, since taking the clicks matters more than the look."""
    made = []

    def blur():
        layer = w.new("BackgroundBlur", owner)
        layer.SetBlurStrength(float(t.BACKDROP_BLUR))
        made.append(layer)

    return made[0] if w.cosmetic("backdrop_blur", blur) else w.border(owner)


def _anchors(left, top):
    """A share of the screen at any resolution: the same margin left and right, top and bottom."""
    return unrealsdk.make_struct("Anchors", Minimum=w.vector(left, top), Maximum=w.vector(1 - left, 1 - top))


def _span(slot, left, top):
    slot.SetAnchors(_anchors(left, top))
    slot.SetOffsets(w.pad(0))


def viewport_slot():
    return unrealsdk.make_struct("GameViewportWidgetSlot", ZOrder=t.ORDER, bAutoRemoveOnWorldRemoved=True,
                                 Alignment=w.vector(0.0, 0.0), Anchors=_anchors(0.0, 0.0), Offsets=w.pad(0))
