# Generated: the settings window Kevin's mods share, taken from Apex Heirloom's and put under this mod's names.
# Its comments may speak of that mod. Never edited by hand: the window's generator writes this file.
# Generated by sync_menu_ui; edit canonical sources.
"""Validated settings transactions; the existing SDK options remain authoritative."""

import math

from . import control_actions, control_config, menu, panel_choices, settings
from .command_actions import Actions
from .command_keys import KEYS
from .panel_preferences import LANGUAGES, language
from .panel_preferences import CONTROLLER_ICONS, controller_icons
from .panel_preferences import last_page
from .panel_preferences import THEMES, theme
from .panel_preferences import SIZES, window_size
from . import panel_toggle

MAX_CHANGES = len(settings.ALL)


class Model:
    # The line the window shows when the ENABLED switch did not take.
    toggle_notice = panel_toggle.FAILED

    def __init__(self, mod):
        self.mod = mod
        self.groups = tuple(menu.MENU)
        # Shown on the COMMANDS page's cards and put back with the keys (menu.COMMAND_SETTINGS).
        self.command_settings = tuple(option for options in menu.COMMAND_SETTINGS.values()
                                      for option in options)
        self.options = {option.identifier: option for option in settings.ALL}
        self._undo = ()
        self.command_actions = Actions(KEYS, mod)

    @property
    def language(self):
        return language.value if language.value in LANGUAGES else language.default_value

    @property
    def can_undo(self):
        return bool(self._undo)

    @property
    def controller_icons(self):
        return controller_icons.value if controller_icons.value in CONTROLLER_ICONS else controller_icons.default_value

    def change_controller_icons(self, value):
        return value in CONTROLLER_ICONS and self.save(((controller_icons, value),))

    @property
    def page(self):
        return last_page.value if last_page.value in menu.SHOWN_PAGES else menu.SHOWN_PAGES[0]

    def change_page(self, value):
        if type(value) is not str or value not in menu.SHOWN_PAGES:
            return False
        return value == last_page.value or self.save(((last_page, value),))

    def save(self, changes):
        previous = tuple((option, option.value) for option, _ in changes)
        try:
            for option, value in changes:
                option.value = value
            self.mod.save_settings()
        except Exception:
            for option, value in previous:
                option.value = value
            try:
                self.mod.save_settings()
            except Exception:
                from . import report
                report.error_once("panel:save", "Settings could not be saved. Please retry.")
            return False
        return True

    def change_language(self, value):
        return value in LANGUAGES and self.save(((language, value),))

    @property
    def theme(self):
        return theme.value if theme.value in THEMES else theme.default_value

    def change_theme(self, value):
        return value in THEMES and self.save(((theme, value),))

    @property
    def window_size(self):
        return window_size.value if window_size.value in SIZES else window_size.default_value

    def change_window_size(self, value):
        return value in SIZES and self.save(((window_size, value),))

    def normalize(self, option, value):
        if type(option.default_value) is bool:
            if type(value) is not bool:
                raise ValueError("Invalid switch")
            return value
        if panel_choices.is_choice(option):
            if type(value) is not str or value not in option.choices:
                raise ValueError("Invalid choice")
            return value
        if type(value) not in (int, float) or not math.isfinite(value):
            raise ValueError("Invalid number")
        if not option.min_value <= value <= option.max_value:
            raise ValueError("Out of bounds")
        steps = round((value - option.min_value) / option.step)
        result = min(option.max_value, max(option.min_value, option.min_value + steps * option.step))
        return int(round(result)) if option.is_integer else round(result, 6)

    def write(self, values):
        if type(values) is not dict or not 0 < len(values) <= MAX_CHANGES:
            return False
        try:
            changes = tuple((self.options[key], self.normalize(self.options[key], value))
                            for key, value in values.items())
        except (KeyError, TypeError, ValueError, OverflowError):
            return False
        if not self.save(changes):
            return False
        self._undo = ()
        return True

    def restore(self):
        options = (*settings.ALL, *control_config.ALL)
        previous = tuple((option, option.value) for option in options)
        if not control_actions.save_values(self.mod, tuple((o, o.default_value) for o in options)):
            return False
        # One bounded undo snapshot; the language is a preference, not a gameplay default.
        self._undo = previous
        return True

    def undo(self):
        if not self._undo or not control_actions.save_values(self.mod, self._undo):
            return False
        self._undo = ()
        return True

    def assign_command(self, action, device, key):
        return self._command_saved(self.command_actions.assign(action, device, key))

    def default_commands(self):
        # The settings shown on the cards are key settings, put back with the keys (Kevin, 2026-10-06).
        held = tuple((option, option.default_value) for option in self.command_settings)
        return self._command_saved(self.command_actions.defaults() and (not held or self.save(held)))

    def _command_saved(self, success):
        if success:
            self._undo = ()
        return success

    def toggle_enabled(self):
        previous = self.mod.is_enabled
        try:
            (self.mod.disable if previous else self.mod.enable)()
            self.mod.save_settings()
        except Exception as error:
            self.toggle_notice = panel_toggle.notice(not previous, error)
            try:
                (self.mod.enable if previous else self.mod.disable)()
                self.mod.save_settings()
            except Exception:
                from . import report
                report.error_once("panel:enable", "Could not restore the mod state. Please retry.")
            return False
        return self.mod.is_enabled != previous
