# Generated: the settings window Kevin's mods share, taken from Apex Heirloom's and put under this mod's names.
# Its comments may speak of that mod. Never edited by hand: the window's generator writes this file.
# Generated by sync_menu_ui; edit canonical sources.
"""Generic window messages generated from Apex Grapple.
"""

TEXT = {'close': 'CLOSE',
 'restore': 'RESTORE DEFAULTS',
 'undo': 'UNDO RESET',
 'enabled': 'ENABLED',
 'disabled': 'DISABLED',
 'on': 'ON',
 'off': 'OFF',
 'by': 'BY',
 'version': 'VERSION',
 'settings': 'SETTINGS',
 'ready': 'Changes are saved automatically. Close returns to the mod list.',
 'saved': 'Saved.',
 'failed': 'Settings could not be saved. Please try again.',
 'toggle_failed': 'The mod could not be switched on or off. Nothing was changed. The reason is in '
                  'unrealsdk.log.',
 'restored': 'Default settings restored. You can undo this reset.',
 'undone': 'Previous settings restored.',
 'refused': 'Assignment refused. This input is reserved or already used.',
 'rollback_abandoned': 'The change was cancelled. Recovery could not be confirmed; restart the '
                       'game before changing settings.',
 'theme': 'THEME:',
 'theme:EMBER': 'EMBER',
 'theme:DARK': 'DARK',
 'theme:LIGHT': 'LIGHT',
 'theme:BL4': 'BL4',
 'theme_later': 'Theme saved. It will show the next time you open this menu.',
 'window_size': 'WINDOW:',
 'window_size:LARGE': 'LARGE',
 'window_size:FULL': 'FULL SCREEN',
 'window_size:NORMAL': 'NORMAL',
 'window_size_later': 'Window size saved. It will show the next time you open this menu.'}
