// Generated by sync_camera_limits.py; edit camera_limits.json instead.
#pragma once

namespace apex_limits {
inline constexpr double loot_base_distance = 330.0;
inline constexpr double loot_max_distance = 990.0;
inline constexpr double shoulder_max_offset = 150.0;
inline constexpr char runtime_folder[] = "_apex_camera_runtime";
}
