"""Values shared by every camera client."""

from .generated_ads import PROTOCOL
MAX_CLIENTS = 8
MAX_PROTOCOL_NOTE_VALUE = (1 << 32) - 1
GAME_MENU_MAX_FOV = 110.0
FOV_MIN = 70.0
FOV_MAX = 150.0
FOV_DEFAULT = 110.0
THIRD_PERSON_RIGHT = 48.4
THIRD_PERSON_UP = 5.0
CAMERA_TRANSITION = "Default"
CAMERA_BLEND = -1.0
CAMERA_TELEPORT = False
FFYL_MODE = "FFYL"
GROUND_SLAM_EXIT_MODE = "GroundSlamExit"
ORBIT_MODE = "Orbit"
THIRD_PERSON_MODE = "ThirdPerson"
CLIMB_MODE = "ThirdPersonClimbing"
LADDER_MODE = "ladder"
SCRIPTED_CLIMB_NONE = 0
SCRIPTED_CLIMB_MAX = 255
