"""Generated by sync_ads_contract.py; edit ads_contract.json instead."""

import ctypes

ADS_ABI = 1
VIEW_ABI = 6
INTERACTION_ABI = 2
CATEGORY_PISTOL = 1
CATEGORY_SMG = 2
CATEGORY_SHOTGUN = 3
CATEGORY_ASSAULT = 4
CATEGORY_SNIPER = 5
CATEGORY_HEAVY = 6
CATEGORY_MAX = 8
MAX_COLLECTORS = 32
MAX_TEXT = 160
MAX_TYPE_BYTES = 1000000
MIN_POINTER = 65536
FOV_OFFSET = 64
MAX_ZOOM_SCALE = 2
OBJECT_INDEX_OFFSET = 12
OBJECT_OUTER_OFFSET = 32
OBJECT_CHUNKS_OFFSET = 16
OBJECT_COUNT_OFFSET = 36
OBJECTS_PER_CHUNK = 65536
OBJECT_ITEM_SIZE = 24
OBJECT_FLAGS_OFFSET = 8
OBJECT_SERIAL_OFFSET = 16
OBJECT_DESTROY_MASK = 270532608
MAX_OBJECTS = 16777216
STATE_INPUTS_OFFSET = 40
INPUTS_CONTROLLER_OFFSET = 232
STATE_MIN_SIZE = 112
INPUTS_MIN_SIZE = 240
CONTROLLER_MIN_SIZE = 1080
WEAPON_MIN_SIZE = 3432
ZOOM_SCALE_RVA = 2347604
HUD_PRODUCER_RVA = 16516506
HUD_GETTER_RVA = 16517686
HUD_GETTER_RETURN_RVA = 16516674
VIEW_UPDATE_RVA = 63785010
VIEW_UPDATE_SLOT = 264
MANAGER_MODE_OFFSET = 14896
MANAGER_MODE_OBJECT_OFFSET = 14920
MANAGER_STATE_OFFSET = 14808
MANAGER_INPUTS_OFFSET = 14800
MODE_BLEND_REMAINING_OFFSET = 2676
MODE_TRANSITION_FLAG_OFFSET = 2680
MODE_GETTER_RVA = 96535832
MODE_FINISH_RVA = 25646020
ANIMATION_WEAPON_OFFSET = 5632
ANIMATION_CATEGORY_OFFSET = 5640
CONTROLLER_MANAGER_OFFSET = 1096
ACTOR_CONTROLLER_LINK_OFFSET = 432
ACTOR_LINK_CONTROLLER_OFFSET = 960
MAX_HASH_FILE_BYTES = 1073741824
MAX_HASH_OBJECT_BYTES = 8192
HASH_BUFFER_BYTES = 65536
MAX_SIGNATURE_BYTES = 64
ERROR_UNSUPPORTED = 1
ERROR_IDENTITY = 2
ERROR_WRONG_THREAD = 3
ERROR_MODE = 4
ERROR_INSTALL = 5
ERROR_CONTEXT = 6
SDK_SHA256 = "d9936cbe3da434743a93e0dadc2f6a5cc82102936c1c249db014a3081fdb4433"
GAME_SHA256 = "9c3afb7dc6a550a6c2e817846cd2c40ff11e066dc6aefeb819f802e6a4c5c3e0"
HUD_PRODUCER_PREFIX = "415741564154565755534881ec80000000"
HUD_GETTER_PREFIX = "5657534883ec204889ce80b92a0d000001"
ZOOM_SCALE_PREFIX = "564881ec900000000f29b42480000000"
MODE_GETTER_PREFIX = "56574883ec284889d74889ce803dad65"
MODE_FINISH_PREFIX = "56574883ec284889cec781740a000000"
VIEW_UPDATE_PREFIX = "4157415641545657534881ec78030000"


class ObjectId(ctypes.Structure):
    _fields_ = [
        ("address", ctypes.c_uint64),
        ("index", ctypes.c_int32),
        ("serial", ctypes.c_int32),
    ]


class PathsConfig(ctypes.Structure):
    _fields_ = [
        ("abi", ctypes.c_uint32),
        ("reserved", ctypes.c_uint32),
        ("state", ctypes.c_uint64),
        ("inputs", ctypes.c_uint64),
        ("controller", ctypes.c_uint64),
        ("weapon", ctypes.c_uint64),
        ("state_size", ctypes.c_uint32),
        ("inputs_size", ctypes.c_uint32),
        ("controller_size", ctypes.c_uint32),
        ("weapon_size", ctypes.c_uint32),
    ]


class PathsSample(ctypes.Structure):
    _fields_ = [
        ("zoom_scale", ctypes.c_float),
        ("crosshair_requested", ctypes.c_uint32),
        ("weapon_present", ctypes.c_uint32),
        ("reserved", ctypes.c_uint32),
    ]


class AdsContext(ctypes.Structure):
    _fields_ = [
        ("abi", ctypes.c_uint32),
        ("size", ctypes.c_uint32),
        ("enabled", ctypes.c_uint32),
        ("reserved", ctypes.c_uint32),
        ("generation", ctypes.c_uint64),
        ("references", ObjectId * 8),
        ("paths", PathsConfig),
    ]


class AdsStats(ctypes.Structure):
    _fields_ = [
        ("generation", ctypes.c_uint64),
        ("producer_calls", ctypes.c_uint64),
        ("getter_calls", ctypes.c_uint64),
        ("reticle_writes", ctypes.c_uint64),
        ("fov_writes", ctypes.c_uint64),
        ("wrong_thread", ctypes.c_uint64),
        ("wrong_mode", ctypes.c_uint64),
        ("identity_refused", ctypes.c_uint64),
        ("restorations", ctypes.c_uint64),
        ("install_attempts", ctypes.c_uint64),
        ("fov_before", ctypes.c_float),
        ("fov_after", ctypes.c_float),
        ("zoom_scale", ctypes.c_float),
        ("reserved", ctypes.c_uint32),
        ("installed", ctypes.c_uint32),
        ("active", ctypes.c_uint32),
        ("pending", ctypes.c_uint32),
        ("error", ctypes.c_uint32),
    ]


class ViewConfig(ctypes.Structure):
    _fields_ = [
        ("abi", ctypes.c_uint32),
        ("duration_ms", ctypes.c_uint32),
        ("slot_index", ctypes.c_uint32),
        ("reserved", ctypes.c_uint32),
        ("expected_rva", ctypes.c_uint64),
        ("right", ctypes.c_double),
        ("up", ctypes.c_double),
    ]


class ViewStats(ctypes.Structure):
    _fields_ = [
        ("calls", ctypes.c_uint64),
        ("writes", ctypes.c_uint64),
        ("rejected", ctypes.c_uint64),
        ("before", ctypes.c_double * 3),
        ("after", ctypes.c_double * 3),
        ("yaw", ctypes.c_double),
        ("active", ctypes.c_uint32),
        ("slot_index", ctypes.c_uint32),
        ("suspended", ctypes.c_uint32),
        ("reserved", ctypes.c_uint32),
        ("ads_effective", ctypes.c_uint32),
        ("ads_error", ctypes.c_uint32),
        ("ads_generation", ctypes.c_uint64),
    ]
