# Generated by sync_menu_ui; edit canonical sources.
"""Generic window messages generated from Apex Grapple.
"""

TEXT = {'close': 'CLOSE',
 'restore': 'RESTORE DEFAULTS',
 'undo': 'UNDO RESET',
 'enabled': 'ENABLED',
 'disabled': 'DISABLED',
 'on': 'ON',
 'off': 'OFF',
 'by': 'BY',
 'version': 'VERSION',
 'settings': 'SETTINGS',
 'ready': 'Changes are saved automatically. Close returns to the mod list.',
 'saved': 'Saved.',
 'failed': 'Settings could not be saved. Please try again.',
 'toggle_failed': 'The mod could not be switched on or off. Nothing was changed. The reason is in '
                  'unrealsdk.log.',
 'restored': 'Default settings restored. You can undo this reset.',
 'undone': 'Previous settings restored.',
 'refused': 'Assignment refused. This input is reserved or already used.',
 'rollback_abandoned': 'The change was cancelled. Recovery could not be confirmed; restart the '
                       'game before changing settings.'}
