"""French Movement pages and settings; common window messages share Grapple's source."""

from .panel_common_fr import TEXT as COMMON

TEXT = {
    **COMMON,
    "camera_refused": "La caméra n’a pas confirmé ce changement. Il n’a pas été enregistré.",
    "camera_timeout": "La caméra n’a pas répondu. Les réglages précédents ont été rétablis. Réessaie dans un moment.",
    "undone_partial": "Réglages rétablis, sauf la caméra : un autre mod la contrôle.",
    "options": "OPTIONS", "options_desc_menu": "Langue du menu.", "languages": "LANGUES",
    # The sentence under the Options title on its camera and commands tabs (Kevin, 2026-10-06).
    "camera_tab_desc": "Vue, visée, caméra orbitale et loot.",
    "commands_tab_desc": "Touches de la caméra, au clavier et à la manette.",
    "camera": "CAMÉRA", "camera_desc": "Vue, champ de vision et loot.",
    # The camera tab's two halves (Kevin, 2026-10-07).
    "camera_view": "VUE CAMÉRA", "shoulder_view": "VUE ÉPAULES", "shoulder": "VUE ÉPAULES",
    "shoulder_tab_desc": "Épaule de la caméra et changement automatique.",
    "shoulder_desc": "Choisis l'épaule, et laisse la caméra changer d'épaule devant un mur.",
    "camera_page": "Vue à pied, champ de vision et vue libre.",
    "aiming": "VISÉE", "aiming_page": "Visée en troisième personne et zoom.",
    "orbit_camera": "CAMÉRA ORBITALE", "orbit_camera_page": "Tourne autour du personnage, à la distance de ton choix.",
    "loot": "LOOT", "loot_page": "Ramasse le loot de plus loin.",
    "dynamic_camera": "CAMÉRA DYNAMIQUE", "dynamic_camera_tab_desc": "Champ de vision, cadrage et mouvements.",
    "dynamic_camera_page": "La caméra suit l'action : vitesse, sauts, accroupi et conduite.",
    "dynamic_fov": "CHAMP DE VISION", "dynamic_fov_desc": "Plus large en sprint et en glissade.",
    "dynamic_framing": "CADRAGE",
    "dynamic_framing_desc": "Recule en courant, en sautant ou en roulant vite, se rapproche accroupi.",
    "dynamic_motion": "MOUVEMENTS", "dynamic_motion_desc": "Une légère inertie, et un faible flottement à l'arrêt.",
    "third_person_needed": "Active la troisième personne dans l'onglet CAMÉRA.",
    "change_key": "MODIFIER", "press_key": "APPUIE SUR UNE TOUCHE", "no_key": "AUCUNE",
    "commands": "COMMANDES", "keyboard": "CLAVIER / SOURIS", "controller": "MANETTE",
    "command_third_person": "TROISIÈME PERSONNE", "command_third_person_desc": "Active ou coupe la vue à la troisième personne.",
    "command_shoulder": "CHANGER D'ÉPAULE", "command_shoulder_desc": "Place la caméra sur l'autre épaule.",
    # One name for the orbit camera, the switch's: « Orbite », « Orbit » and « caméra libre » read as three cameras
    # (review, 2026-09-26).
    "command_orbit": "CAMÉRA ORBITALE", "command_orbit_desc": "Active ou coupe la caméra orbitale.",
    "command_zoom_in": "RAPPROCHER LA CAMÉRA", "command_zoom_in_desc": "Un cran par appui, en caméra orbitale.",
    "command_zoom_out": "ÉLOIGNER LA CAMÉRA", "command_zoom_out_desc": "Un cran par appui, en caméra orbitale.",
    "command_free_look": "VUE LIBRE", "command_free_look_desc": "Maintiens pour tourner la caméra en gardant ta direction.",
    "command_camera_distance": "DISTANCE DE LA CAMÉRA", "command_camera_distance_desc": "Proche, normale ou loin, à la troisième personne.",
    "command_tools": "OPTIONS DES COMMANDES", "command_tools_desc": "Icônes de manette et touches caméra d'origine.",
    "commands_reset": "TOUCHES D'ORIGINE", "controller_icons": "ICÔNES DE MANETTE",
    "camera_draft_discarded": "Mod caméra changé : les réglages caméra non enregistrés ont été annulés.",
    "camera_elsewhere": "Un autre mod contrôle la caméra. Règle-la dans son menu.",
    "framing_saved_unavailable": "Enregistré. Aperçu du cadrage indisponible ici.",
    "framing_saved_partial": "Enregistré. Aperçu du cadrage partiel ici ; consulte les lignes de la caméra.",
    "camera_outdated": "Des mods de caméra de versions différentes sont chargés. Mets à jour Apex Movement, Omni Sprint "
                       "et Third Person & FOV, puis relance le jeu.",
    "right": "DROITE", "left": "GAUCHE",
    "aim_third": "Troisième personne", "aim_first": "Première personne",
    "ads_unsupported": "Visée à l'épaule indisponible avec cette version. Garde la visée première personne jusqu'à une mise à jour du mod.",
    "ads_unknown_weapon": "Arme non reconnue : visée première personne conservée. Essaie une autre arme.",
    "ads_heavy_native": "Armes lourdes : visée première personne conservée.",
    "ads_wrong_thread": "Présentation de visée indisponible : visée première personne conservée. Signale ce problème avec le journal.",
    "ads_mode_unavailable": "Vue de visée non confirmée : visée première personne conservée. Relâche puis reprends la visée.",
    "ads_cleanup_pending": "Retour à la vue du jeu en cours. Attends avant de changer de mod caméra.",
    "ads_install_failed": "Activation de la visée à l'épaule impossible. Relance le jeu ; si cela persiste, signale-le avec le journal.",
    "language": "LANGUE", "menu_language": "LANGUE DU MENU", "language_name": "FRANÇAIS",
    "movement": "DÉPLACEMENT", "auto_sprint": "COURSE AUTOMATIQUE", "slides": "GLISSADES",
    "axle_slide": "GLISSADE AXLE", "dash": "DASH", "glide": "VOL PLANÉ",
    "air_crouch": "FRAPPE AU SOL ET GLISSADE", "air_strafe": "DIRECTION AÉRIENNE",
    "heavier_fall": "CHUTE PLUS LOURDE", "wall_climb": "GRIMPE",
}

GROUPS = {
    "movement": "Vitesse de marche et de course, et la touche de marche lente.",
    "auto_sprint": "Cours automatiquement quand le stick est poussé à fond.",
    "slides": "Départ, distance et vitesse des glissades.",
    "axle_slide": "Dirige et accélère les glissades à la manière d'Axle.",
    "dash": "Distance du dash.",
    "glide": "Vitesse du vol plané.",
    "air_crouch": "Frappe le sol et glisse à l'atterrissage.",
    "air_strafe": "Change rapidement de direction dans les airs.",
    "heavier_fall": "Pesanteur et hauteur des sauts.",
    "wall_climb": "Grimpe, direction et délai avant de se raccrocher.",
}

OPTIONS = {
    "extended_loot": ("Portée du loot augmentée", "Ramasse le loot et ouvre les coffres de plus loin."),
    "loot_reach": ("Portée du loot", "1 : portée du jeu ; 2 : deux fois plus loin."),
    "third_person": ("Troisième personne", "Garde la caméra derrière le personnage à pied."),
    "third_person_ads": ("Visée", "Les fusils de précision et les armes lourdes gardent la visée en première personne."),
    "shoulder_left": ("Changement d'épaule", "Place la caméra à gauche ou à droite du personnage."),
    "shoulder_auto": ("Changement d'épaule automatique",
                      "La caméra passe sur l'autre épaule quand un mur bouche la vue, puis revient."),
    "shoulder_auto_swap": ("Épaule automatique : délai de bascule",
                           "Temps pendant lequel un mur bouche la vue avant que la caméra change d'épaule, en secondes."),
    "shoulder_auto_return": ("Épaule automatique : délai de retour",
                             "Temps de vue dégagée avant que la caméra revienne sur ton épaule, en secondes."),
    "camera_distance_close": ("Distance de la caméra : proche",
                              "Distance derrière toi en position proche, en mètres. La normale est à 2,56."),
    "camera_distance_far": ("Distance de la caméra : loin",
                            "Distance derrière toi en position loin, en mètres. La normale est à 2,56."),
    "shoulder_smooth": ("Changement d'épaule fluide", "Déplace progressivement la caméra entre les deux épaules."),
    "orbit_smooth": ("Transitions caméra fluides", "Anime le décalage ajouté entre première et troisième personne et pour Orbit."),
    "shoulder_seconds": ("Animation de transition", "Durée commune du décalage d'épaule et des transitions caméra, en secondes."),
    "orbit": ("Caméra orbitale", "La caméra tourne librement autour du personnage."),
    "orbit_distance": ("Distance", "Distance de la caméra, aussi réglée par les touches de zoom."),
    "custom_fov": ("FOV personnalisé", "Utilise le FOV ci-dessous à la place de celui du jeu."),
    "fov": ("FOV", "Champ de vision, jusqu'à 150."),
    "speed_fov": ("FOV en vitesse", "Élargit la vue quand tu sprintes."),
    "speed_fov_gain": ("Élargissement", "Champ de vision ajouté en sprint."),
    "speed_fov_seconds": ("Transition", "Secondes pour s'élargir et pour revenir."),
    "action_framing": ("Cadrage selon l'action",
                       "Recule la caméra en courant, en l'air ou en roulant vite, et la rapproche accroupi."),
    "action_framing_strength": ("Force du cadrage", "100 % par défaut ; plus bas, plus doux ; plus haut, plus fort."),
    "camera_motion": ("Mouvements de caméra",
                      "La caméra suit en douceur tes changements de vitesse, et bouge un peu à l'arrêt."),
    "camera_motion_strength": ("Force des mouvements",
                               "100 % par défaut ; plus bas, plus doux ; plus haut, plus fort."),
    "free_look_keyboard_hold": ("Vue libre : maintenir au clavier",
                                "OUI : la vue libre dure tant que la touche est tenue. NON : un appui l'allume, "
                                "un autre l'éteint."),
    "free_look_controller_hold": ("Vue libre : maintenir à la manette",
                                  "OUI : la vue libre dure tant que le bouton est tenu. NON : un appui l'allume, "
                                  "un autre l'éteint."),
    "free_look_hold_time": ("Vue libre : durée du maintien",
                            "Temps à tenir avant que la vue libre démarre, en secondes."),
    "walk_speed": ("Vitesse de marche", "Valeur du jeu : 540."),
    "sprint_speed": ("Vitesse de course", "Valeur du jeu : 828."),
    "auto_sprint": ("Activé", "Courir en poussant le stick à fond."),
    "walk": ("Marche lente",
             "Maintiens la touche pour marcher lentement. Avec la bascule, un seul appui suffit."),
    "walk_toggle": ("Marche lente en bascule",
                    "NON : maintiens la touche pour marcher lentement. OUI : un appui pour marcher lentement, "
                    "un autre pour arrêter."),
    "walk_key_speed": ("Vitesse de la marche lente", "Jusqu'à 540, la marche du jeu."),
    "slides": ("Activé", "Des glissades plus rapides et plus longues."),
    "momentum_slides": ("Suivre l'élan", "La glissade suit ton déplacement au lieu du viseur."),
    "slide_speed": ("Vitesse de départ", "Vitesse au début d'une glissade."),
    "slide_distance": ("Distance sur le plat", "Distance sur terrain plat."),
    "slide_downhill_pull": ("Effet des pentes", "Les pentes accélèrent ou freinent la glissade."),
    "slide_max_speed": ("Vitesse maximale", "Vitesse maximale d'une glissade."),
    "axle_slide": ("Activé", "Des glissades qu'on dirige, et plus rapides, comme Axle."),
    "axle_steering": ("Direction", "Vitesse de rotation d'une glissade avec le stick."),
    "axle_speed_boost": ("Gain de vitesse", "Vitesse en plus, en pourcentage."),
    "axle_flat_distance_boost": ("Distance sur le plat", "Distance en plus sur le plat, en pourcentage."),
    "axle_slope_boost": ("Effet des pentes", "Distance en plus en pente, en pourcentage."),
    "dash": ("Activé", "Un dash plus long."),
    "dash_distance": ("Distance du dash", "En pourcentage. 100 = le dash du jeu."),
    "glide": ("Activé", "Un vol plané plus rapide."),
    "glide_speed": ("Vitesse du vol plané", "En pourcentage. 100 = la vitesse du jeu."),
    "air_crouch": ("Activé", "Frappe avec saut + accroupissement, ou glisse en atterrissant accroupi."),
    "landing_slide_min_speed": ("Vitesse minimale d'arrivée", "Vitesse nécessaire pour glisser à l'atterrissage."),
    "air_strafe": ("Activé", "Change rapidement de direction en l'air et au sol."),
    "air_acceleration": ("Accélération aérienne", "Vitesse à laquelle la direction change en l'air et au sol."),
    "heavier_fall": ("Activé", "Tomber plus vite sans sauter moins haut."),
    "fall_weight": ("Poids de chute", "Force de la gravité. 1 = celle du jeu."),
    "jump_height_bonus": ("Hauteur de saut ajoutée", "Hauteur en plus pour tous les sauts."),
    "wall_climb": ("Activé", "Grimper sur les murs."),
    "climb_height": ("Distance de grimpe", "En pourcentage de la taille du personnage."),
    "climb_speed": ("Vitesse de grimpe", "Vitesse de déplacement sur le mur."),
    "climb_lean": ("Grimpe en diagonale", "Jusqu'où la grimpe peut partir en biais."),
    "reclimb_delay": ("Délai avant une nouvelle grimpe", "Attente avant de pouvoir regrimper. Toucher le sol l'annule."),
}
