# Generated by sync_menu_ui; edit canonical sources.
"""Generic window messages generated from Apex Grapple.
"""

TEXT = {'close': 'FERMER',
 'restore': 'RÉGLAGES D’ORIGINE',
 'undo': 'ANNULER LE RESET',
 'enabled': 'ACTIVÉ',
 'disabled': 'DÉSACTIVÉ',
 'on': 'OUI',
 'off': 'NON',
 'by': 'PAR',
 'version': 'VERSION',
 'settings': 'RÉGLAGES',
 'ready': 'Sauvegarde automatique. Fermer revient à la liste des mods.',
 'saved': 'Enregistré.',
 'failed': 'Impossible d’enregistrer les réglages. Réessaie.',
 'toggle_failed': 'Impossible d’activer ou de désactiver le mod. Rien n’a changé. La raison est '
                  'dans unrealsdk.log.',
 'restored': 'Réglages d’origine restaurés. Tu peux annuler cette restauration.',
 'undone': 'Réglages précédents rétablis.',
 'refused': 'Attribution refusée. Cette touche est réservée ou déjà utilisée.',
 'rollback_abandoned': 'Changement annulé. Le rétablissement n’a pas été confirmé ; relance le jeu '
                       'avant de changer les réglages.'}
